### PR TITLE
Import

### PR DESCRIPTION
**Pull request by gfr10598**
This is pretty much a straight copy from etl to form the basis of etl-gardener.
Only non-copy changes are adding travis submodule, and reworked .travis.yml and README.md.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/2)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Please get the travis CI to pass.

---

Reviewed 9 of 11 files at r1.
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5QYEybUPZfKNib5muX:-L5QYEybUPZfKNib5muY:b-t13s6v) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/.travis.yml#L26)):*
> ```YAML
> # and discover these credentials in the travis logs.
> - if [[ -n "$TEST_SERVICE_ACCOUNT_mlab_testing" ]] ; then
>   echo "$TEST_SERVICE_ACCOUNT_mlab_testing" | base64 -d > travis-testing.key ;
> ```

Let' start without using base64 encoding.

I've sent a new pr to enable a keyname version of deploy_app.sh.

---

*[cmd/gardener/README.md, line 41 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5QaURwhVRiX--7H4HD:-L5QaURx3cYEdCPpSizr:bhvi6wq) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/cmd/gardener/README.md#L41)):*
> ```Markdown
> 
> The default queues feed into etl-ndt-batch pipeline, which pushes rows to
> measurement-lab:batch.ndt.  This table is created by:
> ```

Is `batch.ndt` the ultimate name? I thought this would be `incoming.ndt`? Is that the plan?

---

*[cmd/gardener/README.md, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5Q_b00ez8_w8fWdv7x:-L5Q_b00ez8_w8fWdv7y:bgr5myk) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/cmd/gardener/README.md#L43)):*
> ```Markdown
> measurement-lab:batch.ndt.  This table is created by:
> ```bash
> bq mk --time_partitioning_type=DAY --schema repeated.json -t \
> ```

Please update with location of file name. Please confirm name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-:-L5QbJcEysJOdQgj5m_Y:bqvld21)*

**Comment by gfr10598** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5QYEybUPZfKNib5muX:-L5QkVf64RX2PnU0zAzu:bdy78ic) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/.travis.yml#L26)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Let' start without using base64 encoding.

I've sent a new pr to enable a keyname version of deploy_app.sh.
</blockquote></details>

I spent some time on this yesterday, and never got it to work properly without the base64.  It can't parse the json for some reason.  
I'm happy to add an issue and work on this in PR#3, but don't want to make changes other than deletions in the PR, or get held up trying to fix it at this stage.

---

*[cmd/gardener/README.md, line 41 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5QaURwhVRiX--7H4HD:-L5Qkwb0LsVECY0b25es:bkdwgjf) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/cmd/gardener/README.md#L41)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is `batch.ndt` the ultimate name? I thought this would be `incoming.ndt`? Is that the plan?
</blockquote></details>

That is the plan.  Purpose of this PR is to move code from etl to etl-gardener with minimal edits.  Pretty much just deleting code, except for fixing the for loop issue.

Next PR starts to change the code, and that is a better place to make corrections.

---

*[cmd/gardener/README.md, line 43 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5Q_b00ez8_w8fWdv7x:-L5QlCxOHyanwFmUmSby:bbr2bl4) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/cmd/gardener/README.md#L43)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please update with location of file name. Please confirm name.
</blockquote></details>

Actually I'll just replace this with reference to the etl project, as these details should not be duplicated here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/2)*

**Comment by stephen-soltesz** [comment]
Let's talk this through in person.

---

Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 26 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-L5QYEybUPZfKNib5muX:-L5TyT0HwWpa2FeQGUP2:b-nq5gbd) ([raw file](https://github.com/m-lab/etl-gardener/blob/a8d314bceff3e19819106557387fd9b4c5f63ae7/.travis.yml#L26)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I spent some time on this yesterday, and never got it to work properly without the base64.  It can't parse the json for some reason.  
I'm happy to add an issue and work on this in PR#3, but don't want to make changes other than deletions in the PR, or get held up trying to fix it at this stage.
</blockquote></details>

Yeah, it was tricky discovering how to use the raw key approach.

This should work in this context for a test key.

Note the absence of `$`. The parameter is just the key name from the environment.
```
$TRAVIS_BUILD_DIR/travis/activate_service_account.sh TEST_SERVICE_ACCOUNT_mlab_testing
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-:-L5U012VzzqcZHO-pmA3:bu5sjc5)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 6 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/2#-:-L5U1iVTv_YNSkuw3rBv:bnfp4nl)*

**Pull request merged**
