### PR TITLE
Change datatypes for annotation2 and hopannotation2

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change modifies the supported datatypes for the annotation2 and hopannotation2 datatypes in preparation for processing reannotated or renamed annotation archive types. 

This change updates the configuration to `daily_only: true` for all datatypes, until the complete history of the new datatypes is available again in the public archive.

This change is part of the [Correcting Network Annotations](https://docs.google.com/document/d/1Aro-2G0pGBNfR5sweUcioraik3PXdZRwphwcZzkovB0/edit) design.

This change is part of steps to repair:
* https://github.com/m-lab/data-annotations/issues/34

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/420)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
Remind me again why historical processing needs to stop for all datatypes? Because of the `JOIN`?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/420#-:-NRn857M-0BkHPZZ81bC:bakzyso)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
That's right. There won't be any `annotation2` data until the reannotation process and copy back to GCS is complete.

The option we considered conversationally a few weeks ago (that put etl/gardener changes last) did not account for more data continuing to accumulate that would also need to be renamed. I felt that doing everything once was preferable, rather than two passes since there are already a significant number of manual steps involved.

How does it sound?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/420#-:-NRo12x27B0xfCi_ZUM8:bjvk5vd)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/420#-:-NRo1q3D50ZlXcwHBOhe:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
I additionally updated apply-cluster.sh so staging would process staging data to better validate the annotation2 parsing and join logic on the staging data.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/420#-:-NRoM8Lv5qJeus61Fm-6:b-d3erbi)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
The data is definitely ending up in the annotation2 and hopannotation2 tables. However, the annotation rate isn't stellar but I think that's due to sandbox nodes getting majority operational traffic or non-standard testing. I'll look carefully in staging.

**Pull request merged**
