### PR TITLE
Add daily only option

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a new gardener datatype configuration option for `daily_only: <bool>`. Default behavior is unchanged.

This change refactors the `config` package interface to use standard return type and error propagation, removes a package flag in favor of defining this in the `main` package, and completes unit test coverage of that package.

This change will ultimately allow us to set the pcap processing to "daily only" to prevent the excess reprocessing for historical pcap data. 

This change obsoletes the change started in:
* https://github.com/m-lab/etl-gardener/pull/352

Part of a sequence of changes leading to:
* https://github.com/m-lab/etl-gardener/issues/349

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/388)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
*[`cmd/gardener/gardener.go` line 284 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6OrYPa5DN1THolp7Zi:-N6OrYPa5DN1THolp7Zj:b3vaovu) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/cmd/gardener/gardener.go#L284)):*
> ```Go
> 	// TODO Once the legacy deployments are turned down, this should move to head of main().
> 	gcfg, err := config.ParseConfig(*configPath)
> 	rtx.Must(err, "Failed to parse config: %q", *configPath)
> ```

Per readability guidelines, error strings should not be capitalized.

**Comment by SaiedKazemi** [comment]
*[`config/config.go` line 66 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6Os5F21w3-pvdJq8c0:-N6Os5F21w3-pvdJq8c1:beavu4f) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/config/config.go#L66)):*
> ```Go
> 		return ErrNoConfig
> 	}
> 	f, err := os.Open(name)
> ```

nit: same as above.

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/388)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — COMMENTED** [review]
Thank you! 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/388#-:-N6Ov9IH4Lpx9TjhtKrJ:b-10zgjh)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`cmd/gardener/gardener.go` line 284 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6OrYPa5DN1THolp7Zi:-N6OtHu8Bu13ON-VFQR7:b-pszyrs) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/cmd/gardener/gardener.go#L284)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Per readability guidelines, error strings should not be capitalized.
</blockquote></details>

Since this is `rtx.Must`, I think it may be preferable to think of this like a `log.Fatal` rather than an error. This constructs the final message reported before exiting (and includes the given error as string). Should the same policy apply to this last log message as we apply to error strings?
___
*[`config/config.go` line 56 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6Orko860miryneO7Uf:-N6OuB1j2TI5KrFF3M-f:bx957qb) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/config/config.go#L56)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

nit: just curious why the shorter if err := readFile(name, g) { isn't preferred here.
</blockquote></details>

Good question. I guess I generally don't prefer the `if <clause>; <condition>` pattern. I find it a little harder to scan.
___
*[`config/config.go` line 66 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6Os5F21w3-pvdJq8c0:-N6OuLGtCa2T5W120k1v:b9jbv6a) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/config/config.go#L66)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

nit: same as above.
</blockquote></details>

In this case we actually want `f` not to be locally scoped.
___
*[`config/config_test.go` line 41 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6OsYPCDjLL_aOCRnDR:-N6OudWH5PeJ4SGczNNJ:bi3ym6m) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/config/config_test.go#L41)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

nit: does it make sense to call this "error-no-file-name" to make it more distinguishable form "error-no-such-file"?
</blockquote></details>

Clearer is better. I've updated both names, here and below.

**Comment by SaiedKazemi** [comment]
*[`config/config.go` line 66 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6Os5F21w3-pvdJq8c0:-N6OyjHS7mq3Tyz5sbIb:b-aph8fe) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/config/config.go#L66)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In this case we actually want `f` not to be locally scoped.
</blockquote></details>

I actually deleted this comment because I saw we need `f`.  Not sure why it wasn't removed.

**Comment by SaiedKazemi** [comment]
*[`config/config_test.go` line 41 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/388#-N6OsYPCDjLL_aOCRnDR:-N6OywdGAElj5xjCinQv:b-ucfkn4) ([raw file](https://github.com/m-lab/etl-gardener/blob/cfb4f8b8046b086ac50ea5add7023c2fbe50bd78/config/config_test.go#L41)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clearer is better. I've updated both names, here and below.
</blockquote></details>

Thanks.

**Comment by SaiedKazemi** [comment]
:lgtm:

**Comment by stephen-soltesz** [comment]
(I'll revert the config change before merging) - but wanted to test overnight and over the weekend (if it appears to work) with all types as `daily_only: true`.

**Review by SaiedKazemi — APPROVED** [review]

**Comment by stephen-soltesz** [comment]
Looks like the new behavior WAI over night. I'll leave it over the weekend and expect to be able to revert the config change and merge on Monday.

**Comment by stephen-soltesz** [comment]
This appears to reliably work as intended. I'll revert the config changes (so no types are daily_only:true (but can be in the future)) and merge.

Screen Shot 2022-07-10 at 10 05 32 AM

**Comment by stephen-soltesz** [comment]
FYI: @cristinaleonr - for pcap in the near future.

**Pull request merged**
