### PR TITLE
Basic 2a

### PR DESCRIPTION
**Pull request by gfr10598**
This PR:
  1. Moves some taskqueue related code from batch to could/tq
  2. Deletes code (and unit tests) that is obsolete or not yet needed.
  3. Updates some unit tests to work better in travis.
  4. Adds better unit tests for PostDay, GetBucket.

This is part of refactoring and cleanup related to refinements in the design doc early last week.  The next PR is similar, and then there will be more new code.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/6)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[cloud/tq/tq.go, line 177 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5qZB6JJTbadx1GFMoR:-L5qZB6JJTbadx1GFMoS:b-7anv7q) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L177)):*
> ```Go
> 
> // PostOneTask sends a single https request to the queue pusher to add a task.
> // Iff dryRun is true, this does nothing.
> ```

typo iff/if

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[cloud/tq/tq.go, line 205 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5q_xice5HWLrpe9M7N:-L5q_xice5HWLrpe9M7O:b-hyv0or) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L205)):*
> ```Go
> }
> 
> func (q *Queuer) postWithRetry(queue string, bucket, filepath string) error {
> ```

Add documentation for this func

---

*[cloud/tq/tq.go, line 216 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5qa-faxR5MF5tjIP7e:-L5qa-faxR5MF5tjIP7f:bx890ag) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L216)):*
> ```Go
> 			return err
> 		}
> 		if strings.Contains(err.Error(), "invalid filename") {
> ```

merge this two if ... {} into one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[cloud/tq/tq.go, line 244 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5qdg6nyodWeKDESEaG:-L5qdg6nyodWeKDESEaH:b-2o5do2) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L244)):*
> ```Go
> 		if err != nil {
> 			// TODO - should this retry?
> 			log.Println(err, "on it.Next")
> ```

This log info is confusing to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[cloud/tq/tq.go, line 269 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5qfHxMGbJgHfakvc_-:-L5qfHxMGbJgHfakvc_0:bug0m14) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L269)):*
> ```Go
> // PostDay fetches an iterator over the objects with ndt/YYYY/MM/DD prefix,
> // and passes the iterator to postDay with appropriate queue.
> // Iff wq is not nil, PostDay will call done on wg when finished
> ```

Iff/If

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[cloud/tq/tq_integration_test.go, line 1 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5t7ZXhjgT5DTPedBps:-L5t7ZXhjgT5DTPedBpt:b-5vtp3c) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq_integration_test.go#L1)):*
> ```Go
> // +build integration
> ```

Add TODO for missing unittests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[cmd/gardener/gardener.go, line 128 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5t9lpgzoKf-bfxpUcY:-L5t9lpgzoKf-bfxpUcZ:b-epqht1) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener.go#L128)):*
> ```Go
> 			if v.Tasks == 0 && v.InFlight == 0 {
> 				log.Printf("Ready: %s: %v\n", k, v)
> 				// Should add more tasks now.
> ```

Besides print log info, do you need to return True or do something here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/gardener/gardener.go, line 277 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5tB9BOvgx5TcvXk1xn:-L5tB9BOvgx5TcvXk1xo:bbcld52) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener.go#L277)):*
> ```Go
> 
> 	// Otherwise this is a command line invocation...
> 	log.Println("Command line not implemented")
> ```

Add TODO here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[cmd/gardener/gardener_test.go, line 20 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/6#-L5tBNrPIa-Ggzh6Q7EF:-L5tBNrPIa-Ggzh6Q7EG:bycxwib) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener_test.go#L20)):*
> ```Go
> }
> 
> func Test_getDSClient(t *testing.T) {
> ```

According to https://golang.org/pkg/testing/

TestGetDSClient() is a better name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/6)*

**Comment by gfr10598** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[cloud/tq/tq.go, line 177 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5qZB6JJTbadx1GFMoR:-L5tD4863ZdxZlO5eWYE:be7l33t) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L177)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

typo iff/if
</blockquote></details>

Iff is shorthand for "if and only if".  Not a typo.

---

*[cloud/tq/tq.go, line 205 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5q_xice5HWLrpe9M7N:-L5tDrBvCUwJgQNbBl5S:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L205)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add documentation for this func
</blockquote></details>

Done.

---

*[cloud/tq/tq.go, line 216 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5qa-faxR5MF5tjIP7e:-L5tDrZYhIC7y1RmeGOv:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L216)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

merge this two if ... {} into one
</blockquote></details>

Done.

---

*[cloud/tq/tq.go, line 244 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5qdg6nyodWeKDESEaG:-L5tEpuAyRCv4_VwGtt5:b4kin88) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L244)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

This log info is confusing to me.
</blockquote></details>

Clarified a bit.  Is it clearer?

---

*[cloud/tq/tq.go, line 269 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5qfHxMGbJgHfakvc_-:-L5tCjFFp7QoHL5Hb_N0:bssbbzh) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq.go#L269)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Iff/If
</blockquote></details>

Iff is shorthand for "if and only if".

---

*[cloud/tq/tq_integration_test.go, line 1 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5t7ZXhjgT5DTPedBps:-L5tMdiu4cR82PzEpud8:b-vm3vwe) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cloud/tq/tq_integration_test.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add TODO for missing unittests.
</blockquote></details>

Added unit tests instead.

---

*[cmd/gardener/gardener_test.go, line 20 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5tBNrPIa-Ggzh6Q7EF:-L5tMnej4xVM4zSHecW_:b-9sbhif) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener_test.go#L20)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

According to https://golang.org/pkg/testing/

TestGetDSClient() is a better name.
</blockquote></details>

I haven't been sure how to interpret that reference.  There is also advice in go-nuts about testing the public interface, so the intent is that you should usually test exported functions, and name the test Test{ExportedFunction}.  I haven't  found any clear guidance on naming tests of unexported functions.

The next PR adds a new DataStore package that replaces this function anyway.

Changing name anyway.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6)*

**Comment by gfr10598** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/gardener/gardener.go, line 128 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5t9lpgzoKf-bfxpUcY:-L5tZtLf4pBSAwlVfR0V:ba5dkks) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener.go#L128)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Besides print log info, do you need to return True or do something here?
</blockquote></details>

Removing this code until needed.

---

*[cmd/gardener/gardener.go, line 277 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5tB9BOvgx5TcvXk1xn:-L5t_FgM3nPGL3waz5hS:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener.go#L277)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add TODO here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmd/gardener/gardener_test.go, line 20 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-L5tBNrPIa-Ggzh6Q7EF:-L5yGmprAPnpCPdDAVKl:b-a81j6n) ([raw file](https://github.com/m-lab/etl-gardener/blob/7fb110ffb627f5ba013097f5d9f98f30d736275a/cmd/gardener/gardener_test.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I haven't been sure how to interpret that reference.  There is also advice in go-nuts about testing the public interface, so the intent is that you should usually test exported functions, and name the test Test{ExportedFunction}.  I haven't  found any clear guidance on naming tests of unexported functions.

The next PR adds a new DataStore package that replaces this function anyway.

Changing name anyway.
</blockquote></details>

Thanks for the explanation

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl-gardener/6#-:-L5yHOQ52oAPKpWv_NYJ:bnfp4nl)*

**Pull request merged**
