### PR TITLE
Datastore based Status(), skeleton Process and TaskHandler

### PR DESCRIPTION
**Pull request by gfr10598**
TaskHandler:
1. Create new tasks.
2. Allocate available task queues to new Tasks.
3. Coordinate termination.

It coordinates handling of these events using selects on channels, avoiding other synchronization primitives, aside from a single WaitGroup used to track how many goroutines are in flight.

For handling termination, it also introduces a Terminator object, which is embedded in the larger TaskHandler object. This struct will likely be moved to the m-lab/go repo if it works well, as it may
be generally useful across repos.

Also:
1. GetStatus() to provide status snapshots.

This PR also introduces use of datastore emulator for unit tests in travis.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53)

### CODE REVIEW

**Comment by pboothe** [comment]
Just a few questions.

---

Reviewed 1 of 5 files at r2, 2 of 5 files at r3.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 24 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPTayc2aPjS4irp15U:-LEPTayc2aPjS4irp15V:b-4auwjy) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/README.md#L24)):*
> ```Markdown
> - sleep 2 # allow time for emulator to start up.
> - $(gcloud beta emulators datastore env-init)
> ```
> ```

This ends up screwing up your local environment. I don't want to hold up this PR, but please add a TODO to migrate these tests to docker.

---

*[reproc/dispatch.go, line 31 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPXeM_5UOXkcAPUVGd:-LEPXeMa9Sq4LCiW-rWN:b3ihmck) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L31)):*
> ```Go
> //  Call Wait() to wait until all goroutines have completed.
> type Terminator struct {
> 	semaphore   chan struct{} // Protects the exit initiation.
> ```

"semaphore" is sticking in my craw. Semaphores have up() and down() (or P() and V() if you are dutch). This only has init() and down(). Could you call it `onlyOnce` or something like that?

---

*[reproc/dispatch.go, line 32 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPWiKL-5u93dYPKtbP:-LEPWiKL-5u93dYPKtbQ:b-dqpmft) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L32)):*
> ```Go
> type Terminator struct {
> 	semaphore   chan struct{} // Protects the exit initiation.
> 	terminating chan struct{} // Channel to trigger termination.
> ```

This channel seems redundant? Why not just close the th.taskQueues ?

---

*[reproc/dispatch.go, line 84 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEP_kGLDuKukpD8e_Ft:-LEP_kGLDuKukpD8e_Fu:bdh3hdd) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L84)):*
> ```Go
> }
> 
> // Nop does nothing, but is used for coverage testing.
> ```

Please say more here? I suspect this should be deleted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53#-:-LEPaaQoBWZcC_RMJTTG:b-gpgpt5)*

**Comment by gfr10598** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 24 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPTayc2aPjS4irp15U:-LEQ5WLlBniC-D5phyOL:b-jipxfn) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/README.md#L24)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This ends up screwing up your local environment. I don't want to hold up this PR, but please add a TODO to migrate these tests to docker.
</blockquote></details>

This is screwing up the environment in travis, which is single use.  So this is only a problem if other integration tests need the real datastore, which I'm avoiding.

---

*[reproc/dispatch.go, line 32 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPWiKL-5u93dYPKtbP:-LEQ5fwx2n4D1GHb2oAz:b-p43ftb) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L32)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

This channel seems redundant? Why not just close the th.taskQueues ?
</blockquote></details>

Because then sends to taskQueues would panic.  But I'll look into whether I can make that work.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53)*

**Comment by pboothe** [comment]
*[README.md, line 24 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPTayc2aPjS4irp15U:-LEQZWva6_wFKINl20oF:b-4nttaf) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/README.md#L24)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This is screwing up the environment in travis, which is single use.  So this is only a problem if other integration tests need the real datastore, which I'm avoiding.
</blockquote></details>

Doing the unit tests locally screws up your local environment.  I totally agree about trashing the Travis temp env. It's a bummer when running unit tests in my local shell ends up rendering that shell less usable in some way by leaving behind crucial env variables set to important values and/or running services.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53)*

**Comment by gfr10598** [comment]
Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 24 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEPTayc2aPjS4irp15U:-LER8JReAb1QPG45uiZs:b-3ozf2c) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/README.md#L24)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Doing the unit tests locally screws up your local environment.  I totally agree about trashing the Travis temp env. It's a bummer when running unit tests in my local shell ends up rendering that shell less usable in some way by leaving behind crucial env variables set to important values and/or running services.
</blockquote></details>

Added more clarifying language.

---

*[reproc/dispatch.go, line 84 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEP_kGLDuKukpD8e_Ft:-LER8c1e0hGE-xJfhwuE:b-qpbiln) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L84)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Please say more here? I suspect this should be deleted.
</blockquote></details>

Added TODO that should clarify.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53)*

**Comment by gfr10598** [comment]
PTAL

---

Review status: 3 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53#-:-LERAmwF5qi0bZ6RDO7F:bb71pro)*

**Comment by gfr10598** [comment]
FYI, added a timestamp field to the Task struct.

**Comment by pboothe** [comment]
One last questrion about tests.

---

Review status: 2 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[reproc/dispatch.go, line 84 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEP_kGLDuKukpD8e_Ft:-LEVApiL75AsSYe9BRhR:brd2tq) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L84)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Added TODO that should clarify.
</blockquote></details>

And deleted it ;)

---

*[reproc/dispatch_test.go, line 48 at r4](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEVBT_X4g4W6WwKhkVC:-LEVBT_X4g4W6WwKhkVD:bkaogp6) ([raw file](https://github.com/m-lab/etl-gardener/blob/b40a76827f30bb033708762a3731c5ca7bd4c979/reproc/dispatch_test.go#L48)):*
> ```Go
> }
> 
> func TestWithTaskQueue(t *testing.T) {
> ```

These tests don't verify or assert anything?

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53#-:-LEVBm6xEodLo6hBWzHC:b-d95dil)*

**Comment by gfr10598** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[reproc/dispatch.go, line 84 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEP_kGLDuKukpD8e_Ft:-LEVNWD24AyOruyu7Ntf:b-30dm1c) ([raw file](https://github.com/m-lab/etl-gardener/blob/36b5cd0eaaa18f038b9afe60d2e862cbfdee444c/reproc/dispatch.go#L84)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

And deleted it ;)
</blockquote></details>

Ah - yes this  one was unused.  The one in state.go now has a new comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53)*

**Comment by gfr10598** [comment]
PTAL.

---

Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[reproc/dispatch_test.go, line 48 at r4](https://reviewable.io/reviews/m-lab/etl-gardener/53#-LEVBT_X4g4W6WwKhkVC:-LEVOffm2x2YHPMOZ-n2:bein9t4) ([raw file](https://github.com/m-lab/etl-gardener/blob/b40a76827f30bb033708762a3731c5ca7bd4c979/reproc/dispatch_test.go#L48)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

These tests don't verify or assert anything?
</blockquote></details>

Completion is success.  Added comments.
There isn't much to test, though I suppose I could add some counters.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53#-:-LEVQpTUAMSFY2Qd9hYj:b-83330m)*

**Comment by pboothe** [comment]
:lgtm:

---

Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/53#-:-LEW7xLUDD7IS4hOqyTb:bnfp4nl)*

**Pull request merged**
