### PR TITLE
Adds deduplication code

### PR DESCRIPTION
**Pull request by gfr10598**
Currently just the dedup handler, without hooking it up to the dispatcher.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/26)

### CODE REVIEW

**Comment by pboothe** [comment]
Testing seems a little light? The code that exists LGTM, but I would prefer more tests if possible.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[dispatch/deduphandler.go, line 39 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/26#-L82jn1o1AeroflUhQF3:-L82jn1p5LU0a_WA4kvr:bgssh6e) ([raw file](https://github.com/m-lab/etl-gardener/blob/22f6623da4066dd59409a040710205cdf9bb12d5/dispatch/deduphandler.go#L39)):*
> ```Go
> }
> 
> func assertBasicPipe() {
> ```

As we discussed, this is cool, but please move it to the test file.

---

*[dispatch/deduphandler.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/26#-L83avvcTTTU2HBgBDBU:-L83avvcTTTU2HBgBDBV:bvuo9xr) ([raw file](https://github.com/m-lab/etl-gardener/blob/22f6623da4066dd59409a040710205cdf9bb12d5/dispatch/deduphandler.go#L65)):*
> ```Go
> 			break
> 		}
> 		// Retry roughly every 10 seconds.
> ```

Maybe

`time.Sleep(time.Duration(int(rand.ExpFloat64() / 10.0) + 1) * time.Second)`

to eliminate thundering herds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/26#-:-L83c2d_RssVAuIpYSeD:b6xhtr8)*

**Comment by gfr10598** [comment]
I improved the single test a fair bit.  It is rather ugly with too much knowledge of internals.

I could also expose some of the private methods and test them individually a bit.

---

Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[dispatch/deduphandler.go, line 39 at r1](https://beta.reviewable.io/reviews/m-lab/etl-gardener/26#-L82jn1o1AeroflUhQF3:-L84XxnU-36vFzhLO1l5:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/6da6572dee94f85fe82e0876c4f080d268fc86dd/dispatch/deduphandler.go#L39)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

As we discussed, this is cool, but please move it to the test file.
</blockquote></details>

Done.

---

*[dispatch/deduphandler.go, line 65 at r1](https://beta.reviewable.io/reviews/m-lab/etl-gardener/26#-L83avvcTTTU2HBgBDBU:-L840br6RHAQpneI0xnG:bsa5kgv) ([raw file](https://github.com/m-lab/etl-gardener/blob/6da6572dee94f85fe82e0876c4f080d268fc86dd/dispatch/deduphandler.go#L65)):*
> time.Sleep(time.Duration(int(rand.ExpFloat64() / 10.0) + 1) * time.Second)
I like my formulation better.  I'm not quite sure what yours is supposed to do.  If you think we need subsecond randomness, that would be a different expression.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl-gardener/26#-:-L84YGpy4pe8SKuI0eWl:bis0gcs)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[dispatch/deduphandler.go, line 39 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/26#-L82jn1o1AeroflUhQF3:-L88n29A1BfJWQZU22wI:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/6da6572dee94f85fe82e0876c4f080d268fc86dd/dispatch/deduphandler.go#L39)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[dispatch/deduphandler.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/26#-L83avvcTTTU2HBgBDBU:-L88n490tou_0c7jhcN_:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/6da6572dee94f85fe82e0876c4f080d268fc86dd/dispatch/deduphandler.go#L65)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> time.Sleep(time.Duration(int(rand.ExpFloat64() / 10.0) + 1) * time.Second)
I like my formulation better.  I'm not quite sure what yours is supposed to do.  If you think we need subsecond randomness, that would be a different expression.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/26)*

**Comment by gfr10598** [comment]
TBR.  Submitted without LGTM based on comments.
pboothe please complete review when you get back.

**Comment by pboothe** [comment]
LGTM

**Pull request merged**
