### PR TITLE
Add target Datasets to gardener configuration

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds target datasets to the gardener configuration, making the target output datasets locations controlled entirely by configuration rather than static constants in the gardener code and query templates.

With this change, it will be possible to configure both the gs://archive-measurement-lab source as well as project local archive buckets in sandbox and staging environments (if desired), or to add multiple output locations for development. It will also be possible to output "versioned tables" for breaking schema changes, either with the version in the dataset, e.g. `v2_ndt.ndt7` or with a future change that adds the version as a suffix to the base table, e.g. `ndt.ndt7_v2`.

This change makes the set of tables "joined" with annotation data implicit with the `Datasets.Join` field. Datatypes without this field will not be joined.

Part of:
* https://github.com/m-lab/etl-gardener/issues/349

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
@SaiedKazemi this PR is still a draft, but I would welcome your early feedback.

**Review by stephen-soltesz — COMMENTED** [review]
I can add that the substantive changes are in:
* cloud/bq/ops.go
* config/config.go
* ops/actions.go
* tracker/job.go

The idea being to add a new config option so that all queries/steps in cloud/bq/ops.go parameterized.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390#-:-N6sj1Qu4N8EkcqFvudH:b-fgu0cb)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

**Comment by SaiedKazemi** [comment]
I am not familiar with this repo and do not have much context but the changes looked good to me.  Can you please specify how you tested the changes in the commit message?

:lgtm:

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 8 of 12 files at r1, 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
@cristinaleonr I would welcome your feedback as well.

**Comment by stephen-soltesz** [comment]
Also FYI: @mattmathis - this is one way of supporting "versioned tables" through gardener configuration.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloud/bq/ops.go` line 170 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wzDgg9bfkrfXGE8sC:-N6wzDgg9bfkrfXGE8sD:bast009) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/cloud/bq/ops.go#L170)):*
> ```Go
> }
> 
> const tmpTable = "`{{.Project}}.{{.Job.Datasets.Temp}}.{{.Job.Datatype}}`"
> ```

Nit: The naming is a bit confusing. The dataset name is "tmp," while the variable name is sometimes "tmp" and other times "temp." I think it might make sense to use "tmp" everywhere.
___
*[`config/config.go` line 47 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wyJWB-mpbHdpIoP7v:-N6wyJWB-mpbHdpIoP7w:b-2b8rop) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/config/config.go#L47)):*
> ```Go
> // SetDefaults updates the SourceConfig.Datasets with with default values if necessary.
> func (s *SourceConfig) SetDefaults() {
> 	// NOTE: ideally, this logic should not be done in code. Default configurations
> ```

Could this go in the config? I have a feeling that's something we're trying to move away from, but it seems a little more flexible than defining it in code.
___
*[`tracker/job.go` line 46 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wxFD0-YiJ2UnADFpw:-N6wxFD0-YiJ2UnADFpx:b8thnnt) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/tracker/job.go#L46)):*
> ```Go
> // TablePartition returns the BigQuery table partition for this Job's Date.
> func (j *Job) TablePartition() string {
> 	return j.Datatype + "$" + j.Date.Format("20060102")
> ```

We have this format string in line 114 (and in `gardener.go`). It might be worth saving it in one place.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cloud/bq/ops.go` line 170 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wzDgg9bfkrfXGE8sC:-N6xJ9yWDBEoJ0w9eK58:b-xae774) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/cloud/bq/ops.go#L170)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Nit: The naming is a bit confusing. The dataset name is "tmp," while the variable name is sometimes "tmp" and other times "temp." I think it might make sense to use "tmp" everywhere.
</blockquote></details>

I've updated to use "tmp" throughout.

Is the only confusing part "tmp" vs "temp"?
___
*[`config/config.go` line 47 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wyJWB-mpbHdpIoP7v:-N6xJHfL8ZPiccnzebes:bcl6hcn) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/config/config.go#L47)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Could this go in the config? I have a feeling that's something we're trying to move away from, but it seems a little more flexible than defining it in code.
</blockquote></details>

I've removed `SetDefaults`. I felt conflicted when I added this function. Thank you for this comment.
___
*[`tracker/job.go` line 46 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wxFD0-YiJ2UnADFpw:-N6xJ0JuC8VgD7m-P48N:beij7qr) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/tracker/job.go#L46)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

We have this format string in line 114 (and in `gardener.go`). It might be worth saving it in one place.
</blockquote></details>

We can use this https://github.com/m-lab/go/pull/149

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`tracker/job.go` line 46 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/390#-N6wxFD0-YiJ2UnADFpw:-N6xu05OB4rpqHxHSmnK:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/0c053a2c6b8cfdd4e7e717cbb7d8a4d84d80f049/tracker/job.go#L46)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We can use this https://github.com/m-lab/go/pull/149
</blockquote></details>

Done.

**Comment by stephen-soltesz** [comment]
Okay, I've left this PR as draft b/c there are two down stream dependencies to use this feature:
* the Saver of an earlier gardener version will save Jobs without the Datasets, a datasets-enabled version would load incomplete information. So we need a migration path.
* etl parser writes to an output bucket, but does not include the archive bucket source in the GCS path, only the prefix. By default, this would mix two archive sources into the same GCS output prefix, e.g. ndt/ndt7/2022/01/01/* would include archives from archive-mlab-sandbox and archive-measurement-lab if both were configured sources. I think we want to include the archive source in the output path, e.g. gs://etl-mlab-sandbox/***archive-mlab-sandbox***/ndt/ndt7/2022/**

**Comment by mattmathis** [comment]
Are you using data set table names like tmp_ndt or ndt_tmp?  The documentation and views currency use the latter, but point to the former.  Is this OK?

**Comment by stephen-soltesz** [comment]
@cristinaleonr after a long interlude of dependencies now completed, this change is much more modest than how it started. When you have time, PTAL?

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

Out of curiosity, do you know what happens if one of the datasets doesn't exist?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390#-:-NKJP9vpAVkJIuLM6dLM:b-8g67f3)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`cloud/bq/ops.go` line 154 at r7](https://reviewable.io/reviews/m-lab/etl-gardener/390#-NKJP5aZ3z-9toDXE_s2:-NKJP5aZ3z-9toDXE_s3:b-z4w6sb) ([raw file](https://github.com/m-lab/etl-gardener/blob/41c1db800cf3908b31747274be2d6cfa50ba4b9a/cloud/bq/ops.go#L154)):*
> ```Go
> }
> 
> // CopyToRaw copies the job "temp" table partition to the "raw" table partition.
> ```

Minor: for consistency, I think this should say "tmp".

**Review by stephen-soltesz — COMMENTED** [review]
Very good question. The flexibility of this change highlights the separation between m-lab/etl/cmd/update-schema (which includes a static list of tables and datasets) and this etl-gardener configuration.

Bluesky, we would have a declarative configuration in this repo, that invokes some machinery (TBD) to create the datasets and tables with the correct schema as needed. Today this would be ad-hoc - but to start, this could look something like moving the update-schema command /logic to this repo, making gardener deployments the authoritative source for configured processing and output tables.

If the configured datasets did not exist today, I expect that gardener would attempt to process them, probably send work to the parsers (wastefully), but fail to load data into the non-existent datasets, and then continue (as it does for failures of the common datasets today).

Related: I have not thought through how this would be specified, but however the autoloader agent and gardener-prime (the imaginary version that supports this) agree to process data with JOINs and output locations could also be specified in a similar way to this (or at least in one repo).

@cristinaleonr -- also as I'm writing this I'm realizing that the current gardener join logic depends on the dataset containing both datatypes to be JOIN'd (e.g. ndt7 and annotation are both in the raw_ndt dataset) - would this be the case in an autoloaded model? e.g. for MSAK data.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/390#-:-NKssqZU3nqUYvTgE_Vr:b-q8gd4e)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`cloud/bq/ops.go` line 154 at r7](https://reviewable.io/reviews/m-lab/etl-gardener/390#-NKJP5aZ3z-9toDXE_s2:-NKssJmhD75H7Y9Cm27V:b-82fzpm) ([raw file](https://github.com/m-lab/etl-gardener/blob/41c1db800cf3908b31747274be2d6cfa50ba4b9a/cloud/bq/ops.go#L154)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Minor: for consistency, I think this should say "tmp".
</blockquote></details>

Thank you. Done.

**Pull request merged**
