### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change updates the gardener README with a short overview of this component in the etl data pipeline, and provides example commands for local development, running unit tests, as well as removing (believed) obsolete operational steps (https://github.com/m-lab/etl-gardener/issues/373)

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/374)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
FYI: @SaiedKazemi you might enjoy this change. :)

**Comment by SaiedKazemi** [comment]
___
*[README.md, line 11 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY3MU-1zLVTKJ0_Pvc:-MwY3MU-1zLVTKJ0_Pvd:bqje9ya) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L11)):*
> ```Markdown
> ## Overview
> 
> The v2 date pipeline depends on the gardener for daily and historical
> ```

Should date be data?

**Comment by SaiedKazemi** [comment]
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY3ZNp2DGxizKbTDMp:-MwY3ZNp2DGxizKbTDMq:bgx7dmf) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L21)):*
> ```Markdown
> For both of these modes, gardener issues Jobs (dates) to parsers that request
> them. The parsers will enuemerate all files for that date and parse each, and
> reports status updates to the gardener for the Job date until all are complete.
> ```

Should reports be report?

**Comment by SaiedKazemi** [comment]
___
*[README.md, line 39 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY45Bg3oQjh86gt3Jp:-MwY45Bg3oQjh86gt3Jq:b43uifu) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L39)):*
> ```Markdown
> 
> Gardener maintains a status page on a separate status port, that summarizes
> recent jobs, current state, and any errors. Jobs transition through a standard
> ```

Nit - suggesting s/a/the following/

**Comment by SaiedKazemi** [comment]
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY4SH12C3piX5l8IA1:-MwY4SH12C3piX5l8IA2:bke3ajj) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L43)):*
> ```Markdown
> 
> * Parsing - gardener has issued a job and a parser is working on it.
> * postProcessing - the parser completed parsing a job.
> ```

Nit - suggesting s/post/Post/

**Comment by SaiedKazemi** [comment]
@stephen-soltesz Yes, I enjoyed the change :)  Thanks a lot.  Made a few nitpick suggestions.

**Review by stephen-soltesz — COMMENTED** [review]
Thank you @saiedkazemi -- I'm glad one of us proof read this o.O :D   

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/374#-:-MwYG8Lo2ruoLFqXrPez:b-51h1o5)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr and @SaiedKazemi)

___
*[README.md, line 11 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY3MU-1zLVTKJ0_Pvc:-MwYFaei4wXtyVzzGU5o:bjoe28i) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L11)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Should date be data?
</blockquote></details>

Whoops! Fixed.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY3ZNp2DGxizKbTDMp:-MwYFf_U1mGsUsfDsaZ8:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L21)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Should reports be report?
</blockquote></details>

Done.
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwY4SH12C3piX5l8IA1:-MwYFrIT00PkbiKlW_rZ:bnywp9w) ([raw file](https://github.com/m-lab/etl-gardener/blob/81d2d23c8c83c814dfa908e93281338e25c22650/README.md#L43)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Nit - suggesting s/post/Post/
</blockquote></details>

For better or worse the state in the gardener code is currently `postProcessing`. I've maee the values `code` formatted.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/374)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi and @stephen-soltesz)

___
*[README.md, line 47 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwYHrtd2EMz_T256cyJ:-MwYHrtd2EMz_T256cyK:bk1ivx3) ([raw file](https://github.com/m-lab/etl-gardener/blob/8b4c243b4c28574194d0d678293b1b5c24d631fd/README.md#L47)):*
> ```Markdown
> * `Deduplicating` - gardener deletes duplicate rows from the temporary table.
> * `Copying` - gardener copies rows from the temporary table to the "raw" table.
> * `Deleting` - gardener deletes the temporary table.
> ```

Gardener deletes the temporary table or the job from the temporary table?
___
*[README.md, line 88 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwYIdzyBb51yxkLp4ON:-MwYIdzyBb51yxkLp4OO:bmhoi9d) ([raw file](https://github.com/m-lab/etl-gardener/blob/8b4c243b4c28574194d0d678293b1b5c24d631fd/README.md#L88)):*
> ```Markdown
> ```
> 
> If the `start_time` in the input `test.yml` matches, the parser should begin
> ```

If the `start_time` matches what? Should this be `start_date`?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/374)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr and @SaiedKazemi)

___
*[README.md, line 47 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwYHrtd2EMz_T256cyJ:-MwYQSLzEtvEJOaky7My:bhuu6lo) ([raw file](https://github.com/m-lab/etl-gardener/blob/8b4c243b4c28574194d0d678293b1b5c24d631fd/README.md#L47)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Gardener deletes the temporary table or the job from the temporary table?
</blockquote></details>

Clarified
___
*[README.md, line 88 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/374#-MwYIdzyBb51yxkLp4ON:-MwYQZeyCvSW_zBlvhAd:ba689so) ([raw file](https://github.com/m-lab/etl-gardener/blob/8b4c243b4c28574194d0d678293b1b5c24d631fd/README.md#L88)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

If the `start_time` matches what? Should this be `start_date`?
</blockquote></details>

`start_date` corrected.

... this was a test ... that you've both passed ...  (◠﹏◠)

**Review by cristinaleonr — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/374#-:-MwYS2G2-ibviy9PHR7a:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr and @SaiedKazemi)

**Pull request merged**
