### PR TITLE
Add config changes for hopannotation1 datatype

### PR DESCRIPTION
**Pull request by cristinaleonr**
Adding hopannotation1 config changes back.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/339)

### CODE REVIEW

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/339#-:-Mifd-wj7uO1TgQ0tLNS:bg7igkv)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[config/config.yml, line 21 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/339#-MifcHPb2ks3j7iuR5Ex:-MifcHPb2ks3j7iuR5Ey:bm9l4si) ([raw file](https://github.com/m-lab/etl-gardener/blob/cdb700e817a2da8d77c922a410df319322e6b4b7/config/config.yml#L21)):*
> ```YAML
>   datatype: pcap
>   target: tmp_ndt.pcap
> - bucket: archive-measurement-lab
> ```

Actually, do you want to try running this against archive-mlab-staging?
___
*[config/config.yml, line 24 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/339#-Mifcc_a9DLNVoPganzZ:-Mifcc_a9DLNVoPganz_:bg6or01) ([raw file](https://github.com/m-lab/etl-gardener/blob/cdb700e817a2da8d77c922a410df319322e6b4b7/config/config.yml#L24)):*
> ```YAML
>   experiment: ndt
>   datatype: hopannotation1
>   target: tmp_ndt.hopannotation1
> ```

If I'm not mistaken, we could even set up separate configs for sandbox and staging, and write them to different tables or datasets.
One limitation is that currently all three projects use the same config file, and I think we would only want the archive-measurement-lab config running in prod.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/339)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[config/config.yml, line 21 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/339#-MifcHPb2ks3j7iuR5Ex:-Mj4Pjq5DGe91erGwGWb:b-1ywacc) ([raw file](https://github.com/m-lab/etl-gardener/blob/cdb700e817a2da8d77c922a410df319322e6b4b7/config/config.yml#L21)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Actually, do you want to try running this against archive-mlab-staging?
</blockquote></details>

Thanks for the suggestion, Greg!

I've tried running it locally by changing the bucket in the config to archive-mlab-staging, setting the "PROJECT" env variable to "mlab-staging" and running gardener.go. There were no errors in the terminal, but I did not see any data getting written out to BQ.

`2021/09/08 12:50:05 job.go:506: Unmarshalling 73066`
`2021/09/08 12:50:05 job.go:407: Unmarshalling 47 job/status pairs.`
`2021/09/08 12:50:05 job-service.go:270: {archive-measurement-lab ndt annotation  tmp_ndt.annotation}`
`2021/09/08 12:50:05 job-service.go:270: {archive-measurement-lab ndt ndt7  tmp_ndt.ndt7}`
`2021/09/08 12:50:05 job-service.go:270: {archive-measurement-lab ndt pcap  tmp_ndt.pcap}`
`2021/09/08 12:50:05 job-service.go:270: {archive-mlab-staging ndt hopannotation1  tmp_ndt.hopannotation1}`
`2021/09/08 12:50:05 job-service.go:98: Yesterday starting at 2021-09-08 00:00:00 +0000 UTC`
`2021/09/08 12:50:05 gardener.go:417: Running as manager service`

I also tried pushing the config change to sandbox, but that didn't work either (I would assume because it picks up the "measurement-lab" project).

I believe Saied said he would deploy his changes to prod early this week, so I should soon be able to run it against archive-measurement-lab.
___
*[config/config.yml, line 24 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/339#-Mifcc_a9DLNVoPganzZ:-Mj4WxWlEyAtD6NRRcbf:btvj3p3) ([raw file](https://github.com/m-lab/etl-gardener/blob/cdb700e817a2da8d77c922a410df319322e6b4b7/config/config.yml#L24)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

If I'm not mistaken, we could even set up separate configs for sandbox and staging, and write them to different tables or datasets.
One limitation is that currently all three projects use the same config file, and I think we would only want the archive-measurement-lab config running in prod.
</blockquote></details>

Yes, such a configuration would be useful for testing. I'll bring it up with @stephen-soltesz when he's back.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/339)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[config/config.yml, line 21 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/339#-MifcHPb2ks3j7iuR5Ex:-Mj5Byf43-yJkHdIUXJ_:b-1gb7kx) ([raw file](https://github.com/m-lab/etl-gardener/blob/cdb700e817a2da8d77c922a410df319322e6b4b7/config/config.yml#L21)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Thanks for the suggestion, Greg!

I've tried running it locally by changing the bucket in the config to archive-mlab-staging, setting the "PROJECT" env variable to "mlab-staging" and running gardener.go. There were no errors in the terminal, but I did not see any data getting written out to BQ.

`2021/09/08 12:50:05 job.go:506: Unmarshalling 73066`
`2021/09/08 12:50:05 job.go:407: Unmarshalling 47 job/status pairs.`
`2021/09/08 12:50:05 job-service.go:270: {archive-measurement-lab ndt annotation  tmp_ndt.annotation}`
`2021/09/08 12:50:05 job-service.go:270: {archive-measurement-lab ndt ndt7  tmp_ndt.ndt7}`
`2021/09/08 12:50:05 job-service.go:270: {archive-measurement-lab ndt pcap  tmp_ndt.pcap}`
`2021/09/08 12:50:05 job-service.go:270: {archive-mlab-staging ndt hopannotation1  tmp_ndt.hopannotation1}`
`2021/09/08 12:50:05 job-service.go:98: Yesterday starting at 2021-09-08 00:00:00 +0000 UTC`
`2021/09/08 12:50:05 gardener.go:417: Running as manager service`

I also tried pushing the config change to sandbox, but that didn't work either (I would assume because it picks up the "measurement-lab" project).

I believe Saied said he would deploy his changes to prod early this week, so I should soon be able to run it against archive-measurement-lab.
</blockquote></details>

I think you would need to run it in the mlab-staging gardener cluster, so it has access to the bucket.  It should then be able to write to the mlab-staging tables.  Am I missing something?

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/339)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[config/config.yml, line 21 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/339#-MifcHPb2ks3j7iuR5Ex:-MjF6ib125ZPdSLtZhFy:b-299fdq) ([raw file](https://github.com/m-lab/etl-gardener/blob/cdb700e817a2da8d77c922a410df319322e6b4b7/config/config.yml#L21)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think you would need to run it in the mlab-staging gardener cluster, so it has access to the bucket.  It should then be able to write to the mlab-staging tables.  Am I missing something?
</blockquote></details>

Now that there are data in archive-measurement-lab, I was able to run it against that bucket in sandbox. I verified the BQ table is getting populated with the parsed data.

As discussed offline, we should set up a "projects" variable in the config to be able to read from buckets in different environments, too. Let's do that in a new PR.

**Pull request merged**
