### PR TITLE
Add config metric and "daily" label to gardener_jobs_total metric

### PR DESCRIPTION
**Pull request by cristinaleonr**
1. Add `gardener_config_datatypes` metric.
2. Add a "daily" label to the `gardener_jobs_total` metric to distinguish between daily and historical flow.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/359)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Two questions to consider.

> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/359#-:-Msg3fR4AP2uZJDWgmCd:b-rxvhr8)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[metrics/metrics.go, line 87 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msg1fym5rkMMfY1mkbu:-Msg1fym5rkMMfY1mkbv:bsmlfsu) ([raw file](https://github.com/m-lab/etl-gardener/blob/7e51d3c702c1f2b3a34ac861104198f7b8d536f2/metrics/metrics.go#L87)):*
> ```Go
> 	// Example usage:
> 	// metrics.ConfigDatatypes.WithLabelValues(exp, dt)
> 	ConfigDatatypes = promauto.NewGaugeVec(
> ```

Just to ask so it doesn't go without saying: do we need a new metric? I can see a case either way. Can you say what your rationale was for adding a metric rather than using say `gardener_jobs_total`?
___
*[tracker/job.go, line 160 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msg2MulD-k-vSu4CVUw:-Msg2MulD-k-vSu4CVUx:b4lyvqb) ([raw file](https://github.com/m-lab/etl-gardener/blob/7e51d3c702c1f2b3a34ac861104198f7b8d536f2/tracker/job.go#L160)):*
> ```Go
> 
> // IsDaily returns a string representing whether the job is a Daily job (e.g., job.Date = yesterday).
> func (j Job) IsDaily() string {
> ```

This a refinement comment: please consider this inference logic vs the source of "daily" jobs in https://github.com/m-lab/etl-gardener/blob/master/job-service/job-service.go#L45

This looks like it will work based on the existing behavior of gardener. But, other parts of the system know exactly which jobs are "daily" at creation time; no inference is necessary.

Please comment on the tradeoff you see.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/359)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[metrics/metrics.go, line 87 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msg1fym5rkMMfY1mkbu:-MsgE-H2AoLAybXBYqC9:b-svfvi8) ([raw file](https://github.com/m-lab/etl-gardener/blob/7e51d3c702c1f2b3a34ac861104198f7b8d536f2/metrics/metrics.go#L87)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just to ask so it doesn't go without saying: do we need a new metric? I can see a case either way. Can you say what your rationale was for adding a metric rather than using say `gardener_jobs_total`?
</blockquote></details>

The rationale was that, in the future, if we ever turn processing for a data type off, we wouldn't have any jobs, but the data type would still be configured. Now that you mention it though, I realize we should at least always have daily jobs, so I have removed the metric.
___
*[tracker/job.go, line 160 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msg2MulD-k-vSu4CVUw:-MsgFQ8MDBPQQ4qq4KFY:bpyip2x) ([raw file](https://github.com/m-lab/etl-gardener/blob/7e51d3c702c1f2b3a34ac861104198f7b8d536f2/tracker/job.go#L160)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This a refinement comment: please consider this inference logic vs the source of "daily" jobs in https://github.com/m-lab/etl-gardener/blob/master/job-service/job-service.go#L45

This looks like it will work based on the existing behavior of gardener. But, other parts of the system know exactly which jobs are "daily" at creation time; no inference is necessary.

Please comment on the tradeoff you see.
</blockquote></details>

I agree with you that it's kind of awkward to add extra logic to infer which type of job is under processing, when we already do that on job creation.

I did not find an out of the box method for the jobs to know which type they are. I have added an `IsDaily` field that the `job-service` sets on job creation for daily jobs, and used that instead of the inference.

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/359)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[job-service/job-service.go, line 158 at r4](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msgjpbd4wmNEU8jTES_:-Msgjpbd4wmNEU8jTESa:b-e45god) ([raw file](https://github.com/m-lab/etl-gardener/blob/43d3266f4d1ee0fbac02d1f352ba03d9d449dd9e/job-service/job-service.go#L158)):*
> ```Go
> 	// Check whether there is yesterday work to do.
> 	if j := svc.yesterday.nextJob(ctx); j != nil {
> 		jobCopy := *j
> ```

Hmm, is this necessary?
___
*[metrics/metrics.go, line 87 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msg1fym5rkMMfY1mkbu:-Msggf7S4KsGJpyQJgOU:b83ad08) ([raw file](https://github.com/m-lab/etl-gardener/blob/7e51d3c702c1f2b3a34ac861104198f7b8d536f2/metrics/metrics.go#L87)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

The rationale was that, in the future, if we ever turn processing for a data type off, we wouldn't have any jobs, but the data type would still be configured. Now that you mention it though, I realize we should at least always have daily jobs, so I have removed the metric.
</blockquote></details>

Ooh, that's a good reason. For example, what happens if the scamper1 datatype is retired, the parsing is "up to date", there is no new daily data, and the gardener restarts (resetting the metrics state)? Does the inventory alert compare to the daily tables or historical tables?
___
*[tracker/job.go, line 35 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msgh_zm6VafFHgkPD7i:-Msgh_zm6VafFHgkPD7j:b-ma7evo) ([raw file](https://github.com/m-lab/etl-gardener/blob/984399d8eecacb5db44c8b09d945cc717cab28ec/tracker/job.go#L35)):*
> ```Go
> 	Datatype   string
> 	Date       time.Time
> 	IsDaily    bool `json:",omitempty"`
> ```

Because this is a public field, this will violate the api used between the gardener/etl (similar to how https://github.com/m-lab/etl-gardener/pull/352 started and what I discovered from https://github.com/m-lab/etl-gardener/pull/350) -- once that PR#352 is merged, it should be safer to add new public fields like this, but I think we will still want this one to have the tag `json:"-"`. (this PR won't be safe to merge until PR#352 is also merged). Also, I would prefer that we separate "non- gardener+etl interface" fields at the end of the struct (after `Filter`).

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/359)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[job-service/job-service.go, line 158 at r4](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msgjpbd4wmNEU8jTES_:-Msjs7EVBas5LlasoR1Q:bss4a2b) ([raw file](https://github.com/m-lab/etl-gardener/blob/43d3266f4d1ee0fbac02d1f352ba03d9d449dd9e/job-service/job-service.go#L158)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hmm, is this necessary?
</blockquote></details>

Removed.
___
*[metrics/metrics.go, line 87 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msg1fym5rkMMfY1mkbu:-Msjs8fd6babwXiFDzso:b-55i7xw) ([raw file](https://github.com/m-lab/etl-gardener/blob/7e51d3c702c1f2b3a34ac861104198f7b8d536f2/metrics/metrics.go#L87)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ooh, that's a good reason. For example, what happens if the scamper1 datatype is retired, the parsing is "up to date", there is no new daily data, and the gardener restarts (resetting the metrics state)? Does the inventory alert compare to the daily tables or historical tables?
</blockquote></details>

Sorry, I've made this confusing by mentioning the daily jobs. The inventory alert compares to the historical jobs, but we will output 0 for data types without historical throughput, so all the data types in the query will have a value in the BQ Exporter metric.

The answer to what happens in the scenario where `scamper1` is retired and "up to date" is that the alert would not catch if `scamper1` is in the query or not, so I have added the config metric back.
___
*[tracker/job.go, line 35 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msgh_zm6VafFHgkPD7i:-Msjtj_h9PMgZ2EKmbcT:b-u4ljau) ([raw file](https://github.com/m-lab/etl-gardener/blob/984399d8eecacb5db44c8b09d945cc717cab28ec/tracker/job.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Because this is a public field, this will violate the api used between the gardener/etl (similar to how https://github.com/m-lab/etl-gardener/pull/352 started and what I discovered from https://github.com/m-lab/etl-gardener/pull/350) -- once that PR#352 is merged, it should be safer to add new public fields like this, but I think we will still want this one to have the tag `json:"-"`. (this PR won't be safe to merge until PR#352 is also merged). Also, I would prefer that we separate "non- gardener+etl interface" fields at the end of the struct (after `Filter`).
</blockquote></details>

Right, I think this approach is becoming a bit cumbersome, not to mention it didn't work when I tested it in sandbox. 

I have reverted back to my original approach with an `IsDaily` function, but I made `job.go` and `job-service.go` call the same function to get the daily date.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/359#-:-Msk7psg3cdAqBgFLfWG:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[tracker/job.go, line 35 at r3](https://reviewable.io/reviews/m-lab/etl-gardener/359#-Msgh_zm6VafFHgkPD7i:-Msk7j2M6wKsnKSOzdpP:bccpe8g) ([raw file](https://github.com/m-lab/etl-gardener/blob/984399d8eecacb5db44c8b09d945cc717cab28ec/tracker/job.go#L35)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Right, I think this approach is becoming a bit cumbersome, not to mention it didn't work when I tested it in sandbox. 

I have reverted back to my original approach with an `IsDaily` function, but I made `job.go` and `job-service.go` call the same function to get the daily date.
</blockquote></details>

Awesome.

**Pull request merged**
