### PR TITLE
Refactor dispatch

### PR DESCRIPTION
**Pull request by gfr10598**
Small enhancement to gardener, to support multiple experiments.
Refactor queuehandler code into smaller funcs.
Add metrics.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/19)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 2 of 8 files at r1, 1 of 6 files at r2.
Review status: 3 of 7 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[cloud/tq/queuehandler.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f8UB6H4dyBQqiYGF5:-L7f8UB6H4dyBQqiYGF6:b-ye6awv) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L50)):*
> ```Go
> 
> // waitForEmptyQueue loops checking queue until empty.
> func (chq *ChannelQueueHandler) waitForEmptyQueue() {
> ```

The `chq` acronym looks like the letters are out of order wrt the type name? I grant you chq is easier to type :)  Just `qh` might be okay too.

---

*[cloud/tq/queuehandler.go, line 62 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f7uftoq0tG-ghkfNE:-L7f7uftoq0tG-ghkfNF:b-se25p1) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L62)):*
> ```Go
> 			// or perhaps the queue_pusher is down.
> 			log.Println(err)
> 			metrics.ErrorCount.WithLabelValues("IsEmptyError")
> ```

Probably want +`.Inc()` throughout.

What does "TODO update metric" mean?

---

*[cloud/tq/queuehandler.go, line 72 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f97loaB6VwR-wORtj:-L7f97loaB6VwR-wORtk:b1wqfxz) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L72)):*
> ```Go
> func (chq *ChannelQueueHandler) processOneRequest(prefix string, bucketOpts ...option.ClientOption) error {
> 	// Use proper storage bucket.
> 	parts, err := parsePrefix(prefix)
> ```

I think it may be time (in general, not necessarily this PR) to create a package to wrap processing these paths and archive names. etl, etl-embargo, and etl-gardener all have their own logic.

---

*[cloud/tq/queuehandler.go, line 98 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f7CmKDKa0U-oLQEDU:-L7f7CmKDKa0U-oLQEDV:b-3lc57u) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L98)):*
> ```Go
> 
> 		prefix, more := <-chq.Channel
> 		if more {
> ```

Please restructure this block to read like:

```
if !more {
   close(done)
   break
}
// handle positive case.
```

This structure mirrors the common go error handling pattern.

---

*[cloud/tq/queuehandler.go, line 100 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f5xiesqUFkyxxx0SB:-L7f5xiesqUFkyxxx0SC:b2g3es8) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L100)):*
> ```Go
> 		if more {
> 			err := chq.processOneRequest(prefix, bucketOpts...)
> 			if err == nil {
> ```

Is this condition correct? nil is an error? Or is this a place holder for additional behavior in the future? Please add a TODO if so. Currently ignoring the `err != nil` case.

---

*[dispatch/dispatch.go, line 101 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f4iFjrKxKrumi7_cA:-L7f4iFjrKxKrumi7_cB:b-h5oc6m) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/dispatch/dispatch.go#L101)):*
> ```Go
> 
> 		next = next.AddDate(0, 0, 1)
> 		// When we catch up to two days ago, start over.
> ```

Please rephrase; I had to do a double take. I understand this as "once gardener process all dates up to two days ago, start over from the beginning."

---

*[dispatch/dispatch_test.go, line 35 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f38c0vMBAaT9bJIUW:-L7f38c0vMBAaT9bJIUX:b-pc9aze) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/dispatch/dispatch_test.go#L35)):*
> ```Go
> 	d.Terminate()
> 
> 	// Test prefix should have triggered a single task queue check, so count should be 2.
> ```

"should be 6"?

---

*[k8s/data-processing-cluster/deployments/etl-gardener.yml, line 47 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f42MpyZ0nXLf0wz9m:-L7f42MpyZ0nXLf0wz9n:bz192tn) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/k8s/data-processing-cluster/deployments/etl-gardener.yml#L47)):*
> ```YAML
>           value: "archive-{{GCLOUD_PROJECT}}"
>         - name: EXPERIMENTS
>           value: "ndt"  # For example "ndt,sidestream,disco"
> ```

It looks like this value is used in the GCS bucket path. So, in the case of disco data it should be "switch".

We should consider normalizing the names used throughout the pipeline for experiment collection, archival, parser data types, and destination tables. This will take work but it will prevent confusion in cases like this or ad-hoc translation tables. 

---

*[metrics/metrics.go, line 13 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f5ReE6oLkKEurkayY:-L7f5ReE6oLkKEurkayZ:b-yutstx) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L13)):*
> ```Go
> 
> var (
> 	// ErrorCount counts non-fatal errors.
> ```

What is the difference between a non-fatal error and a warning?

---

*[metrics/metrics.go, line 21 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f2LTKjINyCe0BxXj6:-L7f2LTKjINyCe0BxXj7:ba3h5x7) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L21)):*
> ```Go
> 	ErrorCount = prometheus.NewCounterVec(
> 		prometheus.CounterOpts{
> 			Name: "etl_error_count",
> ```

I recommend prefixing these with `gardener_` to indicate they're from this service as distinct from the etl parsers.

---

*[metrics/metrics.go, line 27 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f2ppNV9jNoeTubPHb:-L7f2ppNV9jNoeTubPHc:b-xglm6f) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L27)):*
> ```Go
> 	)
> 
> 	// WarningCount counts the number of files processed with each status.
> ```

Is this comment accurate?

---

*[metrics/metrics.go, line 41 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f2sJet1yw9cp4C1FC:-L7f2sJet1yw9cp4C1FD:b-xglm6f) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L41)):*
> ```Go
> 	)
> 
> 	// FailCount counts the number of files processed with each status.
> ```

Is this comment accurate?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/19)*

**Comment by gfr10598** [comment]
Review status: 3 of 7 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[cloud/tq/queuehandler.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f8UB6H4dyBQqiYGF5:-L7fAyePm2TvPflxJpof:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The `chq` acronym looks like the letters are out of order wrt the type name? I grant you chq is easier to type :)  Just `qh` might be okay too.
</blockquote></details>

Done.

---

*[cloud/tq/queuehandler.go, line 62 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f7uftoq0tG-ghkfNE:-L7fAtUNcKF-qewtUJww:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L62)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Probably want +`.Inc()` throughout.

What does "TODO update metric" mean?

</blockquote></details>

Done.

---

*[cloud/tq/queuehandler.go, line 72 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f97loaB6VwR-wORtj:-L7fFA-w9bF5pXLsRaWK:bb82la3) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L72)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I think it may be time (in general, not necessarily this PR) to create a package to wrap processing these paths and archive names. etl, etl-embargo, and etl-gardener all have their own logic.
</blockquote></details>

Created an issue #21 

---

*[cloud/tq/queuehandler.go, line 98 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f7CmKDKa0U-oLQEDU:-L7fB8sePj-6YWFeOzkg:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L98)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please restructure this block to read like:

```
if !more {
   close(done)
   break
}
// handle positive case.
```

This structure mirrors the common go error handling pattern.
</blockquote></details>

Done.

---

*[cloud/tq/queuehandler.go, line 100 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f5xiesqUFkyxxx0SB:-L7fBGgayirxKS5LhU0X:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/cloud/tq/queuehandler.go#L100)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this condition correct? nil is an error? Or is this a place holder for additional behavior in the future? Please add a TODO if so. Currently ignoring the `err != nil` case.
</blockquote></details>

Done.

---

*[dispatch/dispatch.go, line 101 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f4iFjrKxKrumi7_cA:-L7fB_XOQz9XPGpo4LA0:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/dispatch/dispatch.go#L101)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please rephrase; I had to do a double take. I understand this as "once gardener process all dates up to two days ago, start over from the beginning."
</blockquote></details>

Done.

---

*[dispatch/dispatch_test.go, line 35 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f38c0vMBAaT9bJIUW:-L7fDGHuzvDKviLHJrCg:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/dispatch/dispatch_test.go#L35)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"should be 6"?
</blockquote></details>

Done.

---

*[k8s/data-processing-cluster/deployments/etl-gardener.yml, line 47 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f42MpyZ0nXLf0wz9m:-L7fFWFLdZtJzj2BbPrO:b-d602s) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/k8s/data-processing-cluster/deployments/etl-gardener.yml#L47)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It looks like this value is used in the GCS bucket path. So, in the case of disco data it should be "switch".

We should consider normalizing the names used throughout the pipeline for experiment collection, archival, parser data types, and destination tables. This will take work but it will prevent confusion in cases like this or ad-hoc translation tables. 
</blockquote></details>

Fixed.  Created #471 in etl repo.

---

*[metrics/metrics.go, line 13 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f5ReE6oLkKEurkayY:-L7fEY2N2ih5fa6N_Xhg:br98svs) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is the difference between a non-fatal error and a warning?
</blockquote></details>

Good question.  Removed.

---

*[metrics/metrics.go, line 21 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f2LTKjINyCe0BxXj6:-L7fDZjaWYOqlv1CO8nh:bm747ax) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend prefixing these with `gardener_` to indicate they're from this service as distinct from the etl parsers.
</blockquote></details>

Done.
BTW, will prometheus find these collection targets?

---

*[metrics/metrics.go, line 27 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f2ppNV9jNoeTubPHb:-L7fEV8bWPjMbxzZC7gJ:bt2vr0b) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L27)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this comment accurate?
</blockquote></details>

Fixed

---

*[metrics/metrics.go, line 41 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-L7f2sJet1yw9cp4C1FC:-L7fEWe1suEn5mi9YVaD:b-lx4fjp) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L41)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this comment accurate?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/19)*

**Comment by gfr10598** [comment]
PTAL

---

Review status: 1 of 8 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/19#-:-L7fG5amRbQ91fq6UMTr:b-83331m)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r2, 1 of 7 files at r3.
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[metrics/metrics.go, line 21 at r2](https://beta.reviewable.io/reviews/m-lab/etl-gardener/19#-L7f2LTKjINyCe0BxXj6:-L7fHkdfAv0L0u2stadG:b-5ue9kw) ([raw file](https://github.com/m-lab/etl-gardener/blob/7eacd2546cfd42453f549c8c81f15a3f617d48f6/metrics/metrics.go#L21)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done.
BTW, will prometheus find these collection targets?
</blockquote></details>

Good question. Since we're running gardener in a new cluster -- I'll have to setup additional collection from there. The steps should be: 1) add new prometheus cluster config (like scraper & downloader) to data processing cluster, 2) add new federated scrape configs in the federated config.

Created: https://github.com/m-lab/prometheus-support/issues/199

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/etl-gardener/19#-:-L7fJAXx0Ma3eMc_H2W7:bnfp4nl)*

**Pull request merged**
