### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by gfr10598**
Fixes some test auth problems.
Adds go get imports to travis
Adds docker config and build
Adds a k8s config and deployment.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/9)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 11 files at r1.
Review status: 1 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 23 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NhlQuOsoYhKHPPRs8:-L6NhlQuOsoYhKHPPRs9:b2a0lju) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/.travis.yml#L23)):*
> ```YAML
> 
> # Install test credentials.
> # These are uploaded to travis by doing this from within the repository ... TODO
> ```

What is TODO?

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NiQBOs3bAy9H0gK23:-L6NiQBOs3bAy9H0gK24:b-g98gy0) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/.travis.yml#L30)):*
> ```YAML
>   $TRAVIS_BUILD_DIR/travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_testing ;
>   echo "$SERVICE_ACCOUNT_mlab_testing" > $TRAVIS_BUILD_DIR/creds.json ;
>   export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/creds.json ;
> ```

We could modify activate_service_account.sh to take an optional filename to write the contents to.

---

*[apply-cluster.sh, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6Nm_9COrCK2SzcboVX:-L6Nm_9COrCK2SzcboVY:by6asbx) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/apply-cluster.sh#L20)):*
> ```Shell
> 
> # Check for per-project template variables.
> if [[ ! -f "k8s/${CLUSTER}/${PROJECT}.yml" ]] ; then
> ```

Do we need this block any more? ... actually why didn't this cause your travis build to fail?

---

*[apply-cluster.sh, line 28 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NmpuyHHqQDTlON3Nw:-L6NmpuyHHqQDTlON3Nx:bb08060) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/apply-cluster.sh#L28)):*
> ```Shell
> # Apply templates
> CFG=/tmp/${CLUSTER}-${PROJECT}.yml
> kexpand expand --ignore-missing-keys k8s/${CLUSTER}/*.yml \
> ```

Is this an old version? This is not the pattern needed to match files that we worked out at your workstation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/9)*

**Comment by gfr10598** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[.travis.yml, line 23 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NhlQuOsoYhKHPPRs8:-L6OOr-9j8QAE8cQllEc:b-bw8e14) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/.travis.yml#L23)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What is TODO?
</blockquote></details>

Updated.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NiQBOs3bAy9H0gK23:-L6ONfQZsjM1HicPcOCV:b-82csrg) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/.travis.yml#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We could modify activate_service_account.sh to take an optional filename to write the contents to.
</blockquote></details>

Actually, it now looks like probably don't need to activate here, just need to create the file and set the credentials env var.

Do you think that is worth another script, or incorporating into the existing script?

---

*[apply-cluster.sh, line 20 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6Nm_9COrCK2SzcboVX:-L6OM5DPSg6Mixp6_aql:bnymfyx) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/apply-cluster.sh#L20)):*
> activate_service_account
It did and I removed it.

---

*[apply-cluster.sh, line 28 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NmpuyHHqQDTlON3Nw:-L6OMDEaf7qiOaR1s6nt:bj1ahpe) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/apply-cluster.sh#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is this an old version? This is not the pattern needed to match files that we worked out at your workstation.
</blockquote></details>

Not sure how that slipped in.  Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/9)*

**Comment by gfr10598** [comment]
PTAL

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-:-L6SZ8TuFPmj-j-m8RLW:bb71pro)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 4 of 11 files at r1.
Review status: 4 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[.travis.yml, line 30 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6NiQBOs3bAy9H0gK23:-L6SsqqdVh57KZ6HTAlC:b5rvtu3) ([raw file](https://github.com/m-lab/etl-gardener/blob/0438a32acfb2f5c02fc7766d4c0a3f74bcc18d11/.travis.yml#L30)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Actually, it now looks like probably don't need to activate here, just need to create the file and set the credentials env var.

Do you think that is worth another script, or incorporating into the existing script?
</blockquote></details>

No, looks good.

---

*[apply-cluster.sh, line 38 at r3](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6StKXnTcagF00nCLsB:-L6StKXnTcagF00nCLsC:b6ybwpr) ([raw file](https://github.com/m-lab/etl-gardener/blob/226f1405e4649ec6fc6bd56bcf4f61806ea1d0c6/apply-cluster.sh#L38)):*
> ```Shell
>   # Reload configurations. If the deployment configuration has changed then this
>   # request may fail because the container has already shutdown.
>   curl -X POST http://${PUBLIC_IP}:8080/-/reload || :
> ```

Reload applies to prometheus. This probably isn't necessary for gardener. If we're using a static IP, then this entire query can be removed.

---

*[Dockerfile, line 9 at r3](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6StkVQaaq4Z6Kd54sR:-L6StkVQaaq4Z6Kd54sS:b-f8g51f) ([raw file](https://github.com/m-lab/etl-gardener/blob/226f1405e4649ec6fc6bd56bcf4f61806ea1d0c6/Dockerfile#L9)):*
> ```Dockerfile
> COPY . .
> 
> RUN go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v etl-gardener)
> ```

Please add a comment describing this command.

---

*[k8s/data-processing-cluster/services/etl-gardener-service.yml, line 17 at r3](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6SuGHyf9-YKtBFxuqT:-L6SuGHyf9-YKtBFxuqU:bohsreq) ([raw file](https://github.com/m-lab/etl-gardener/blob/226f1405e4649ec6fc6bd56bcf4f61806ea1d0c6/k8s/data-processing-cluster/services/etl-gardener-service.yml#L17)):*
> ```YAML
>   externalIPs:
>   - {{EXTERNAL_IP}}
>   type: LoadBalancer
> ```

Does this work with an explicit external ip? If so, this may obviate a step I need to take with the ClusterIP approach in prometheus.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-:-L6TE6kKV_Fwl7qeIS2Q:bnfp4nl)*

**Comment by gfr10598** [comment]
Review status: 4 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[apply-cluster.sh, line 38 at r3](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6StKXnTcagF00nCLsB:-L6TUU40WeGXo0CfH1Z-:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/226f1405e4649ec6fc6bd56bcf4f61806ea1d0c6/apply-cluster.sh#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Reload applies to prometheus. This probably isn't necessary for gardener. If we're using a static IP, then this entire query can be removed.
</blockquote></details>

Done.

---

*[Dockerfile, line 9 at r3](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6StkVQaaq4Z6Kd54sR:-L6TV1BbyZrb24_l11nU:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/226f1405e4649ec6fc6bd56bcf4f61806ea1d0c6/Dockerfile#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment describing this command.
</blockquote></details>

Done.

---

*[k8s/data-processing-cluster/services/etl-gardener-service.yml, line 17 at r3](https://reviewable.io:443/reviews/m-lab/etl-gardener/9#-L6SuGHyf9-YKtBFxuqT:-L6TUCivE6J1zoacD1bv:b-wva7kp) ([raw file](https://github.com/m-lab/etl-gardener/blob/226f1405e4649ec6fc6bd56bcf4f61806ea1d0c6/k8s/data-processing-cluster/services/etl-gardener-service.yml#L17)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this work with an explicit external ip? If so, this may obviate a step I need to take with the ClusterIP approach in prometheus.
</blockquote></details>

I haven't gotten it to work.  But I did find the gcloud provided IP I can use to connect to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/9)*

**Pull request merged**
