### PR TITLE
Add gardener configuration for ndt/hopannotation1

### PR DESCRIPTION
**Pull request by cristinaleonr**
- Added hopannotation1 entry to Gardener config.
- Prevented hopannotation1 data from being joined (for now).

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - but probably don't merge until https://github.com/m-lab/etl/pull/1015 is also merged.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338#-:-Mh_Kist8GaoqZmdW5gv:b5upaxw)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/config.yml, line 24 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/338#-Mh_LEMx49hv8KOWQBPm:-Mh_LEMx49hv8KOWQBPn:b3wsu5m) ([raw file](https://github.com/m-lab/etl-gardener/blob/3a2265a735387d5713feaa5248a4c2979f4e7bdb/config/config.yml#L24)):*
> ```YAML
>   experiment: ndt
>   datatype: hopannotation1
>   target: tmp_ndt.hopannotation1
> ```

Actually until there is data, we should not add the config, right? Otherwise it's just busy looping looking for data that's not there?

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/config.yml, line 24 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/338#-Mh_LEMx49hv8KOWQBPm:-Mh_Mi8A0Bc1Zc_QFmuc:b-egblk8) ([raw file](https://github.com/m-lab/etl-gardener/blob/3a2265a735387d5713feaa5248a4c2979f4e7bdb/config/config.yml#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Actually until there is data, we should not add the config, right? Otherwise it's just busy looping looking for data that's not there?
</blockquote></details>

Just commenting this out could work.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/config.yml, line 24 at r1](https://reviewable.io/reviews/m-lab/etl-gardener/338#-Mh_LEMx49hv8KOWQBPm:-MhkB-8V1oDZE22Tcjse:b-fba7sv) ([raw file](https://github.com/m-lab/etl-gardener/blob/3a2265a735387d5713feaa5248a4c2979f4e7bdb/config/config.yml#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just commenting this out could work.
</blockquote></details>

Commented it out!

**Review by stephen-soltesz — APPROVED** [review]
Thank you for adding the TODO. One small suggestion for phrasing. 

:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338#-:-MhkOZFR0PBb7m57MeOq:b-nd4lun)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[config/config.yml, line 21 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/338#-MhkOG-yEPoFvAW2WLOr:-MhkOG-yEPoFvAW2WLOs:b-kcu4oo) ([raw file](https://github.com/m-lab/etl-gardener/blob/a58bfd5864d877025e94e57a98db9a1452944d55/config/config.yml#L21)):*
> ```YAML
>   datatype: pcap
>   target: tmp_ndt.pcap
> # TODO(cristinaleon): Uncomment the hopannotation1 entry once the traceroute work is done
> ```

... "Uncomment once the traceroute with hopannotation1 deployment is in production."

I think that's specific enough to help someone not us know when it was okay to uncomment this config.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/338)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[config/config.yml, line 21 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/338#-MhkOG-yEPoFvAW2WLOr:-MhkPLN-3tzMx27dq2rz:b-8fx2u7) ([raw file](https://github.com/m-lab/etl-gardener/blob/a58bfd5864d877025e94e57a98db9a1452944d55/config/config.yml#L21)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

... "Uncomment once the traceroute with hopannotation1 deployment is in production."

I think that's specific enough to help someone not us know when it was okay to uncomment this config.
</blockquote></details>

:+1:

**Pull request merged**
