### PR TITLE
Add BasicPipe interface

### PR DESCRIPTION
**Pull request by gfr10598**
This introduces a very simple interface for cascading tasks through a series of goroutines.

We should also look into using https://github.com/trustmaster/goflow

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/25)

### CODE REVIEW

**Comment by pboothe** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[api/api.go, line 23 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/25#-L7z9B3vZizkqQBkXvEY:-L7z9B3vZizkqQBkXvEZ:blmd2lw) ([raw file](https://github.com/m-lab/etl-gardener/blob/0b7c5f3b9f1cb0e3b071e6de973f2b536bc3be84/api/api.go#L23)):*
> ```Go
> }
> 
> func assertBasicPipe(ds BasicPipe) {
> ```

Is this a normal Go idiom? Because it's weird, but I think I understand it: It forces type-checking to check that one type is-a other type.

---

*[dispatch/dispatch_test.go, line 40 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/25#-L7zACn9hgmFpj9vK3nQ:-L7zACn9hgmFpj9vK3nR:b-utxbpd) ([raw file](https://github.com/m-lab/etl-gardener/blob/0b7c5f3b9f1cb0e3b071e6de973f2b536bc3be84/dispatch/dispatch_test.go#L40)):*
> ```Go
> 
> 	// Count should be 6 (HTTP gets)
> 	// TODO - this is failing about 1 in 500 times.  Race condition?
> ```

Yes. A race between the shutdown routine calling close() versus actually finishing. If you really care about this, then the `sync` module may be of assistance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/25)*

**Comment by pboothe** [comment]
Looks good, but I want to make sure we affirmatively decide to care or not-care about the race condition before I click the LGTM button

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/25#-:-L7zB7ZIyobNFg5ma4Ri:bc7z504)*

**Comment by pboothe** [comment]
:lgtm: once the Todo is updated

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/25#-:-L7zf4NruheOAfshQIxV:bb7oiu8)*

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[api/api.go, line 23 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/25#-L7z9B3vZizkqQBkXvEY:-L7zZXSGvD2CKzF0_olY:b70qyfc) ([raw file](https://github.com/m-lab/etl-gardener/blob/0b7c5f3b9f1cb0e3b071e6de973f2b536bc3be84/api/api.go#L23)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Is this a normal Go idiom? Because it's weird, but I think I understand it: It forces type-checking to check that one type is-a other type.
</blockquote></details>

No idea if it is normal.  Just discovered/created it last week.

---

*[dispatch/dispatch_test.go, line 40 at r1](https://reviewable.io:443/reviews/m-lab/etl-gardener/25#-L7zACn9hgmFpj9vK3nQ:-L8-5sD0DBvSHY-AjCTX:b-5emhe0) ([raw file](https://github.com/m-lab/etl-gardener/blob/0b7c5f3b9f1cb0e3b071e6de973f2b536bc3be84/dispatch/dispatch_test.go#L40)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Yes. A race between the shutdown routine calling close() versus actually finishing. If you really care about this, then the `sync` module may be of assistance.
</blockquote></details>

I'm adding a mutex around the terminate related code.  It doesn't resolve the race, but it does make the code obviously safer.
After adding the lock, I'm now quite confused why the race still seems to exist.  Spent an hour trying to understand it better, and still can't see what the problem is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/25)*

**Pull request merged**
