### PR TITLE
Add action to join with annotations

### PR DESCRIPTION
**Pull request by gfr10598**
This adds the action to join each table (except annotation) with the annotation table.
It imposes a condition that delays the join until the annotation table processing has completed.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/314)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/314)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[ops/actions.go, line 31 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGt_wPw9vQP5B54Zsfd:-MGt_wPw9vQP5B54Zsfe:b-f9rsvz) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L31)):*
> ```Go
> // This returns a ConditionFunc that checks for completion of corresponding
> // annotation job in the tracker.
> func newCondFunc(tk *tracker.Tracker, detail string) ConditionFunc {
> ```

Please choose a more descriptive function name. e.g. newAnnotationCondFunc?  `newCondFunc` is too generic to be clear about what's happening at call sites.
___
*[ops/actions.go, line 33 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtZMaKCS3i4-6GudYs:-MGtZMaKCS3i4-6GudYt:b-gqydz4) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L33)):*
> ```Go
> func newCondFunc(tk *tracker.Tracker, detail string) ConditionFunc {
> 	return func(ctx context.Context, j tracker.Job) bool {
> 		if j.Datatype == "annotation" {
> ```

Please add a comment -- I'm guessing this makes the annotation table always available to itself?
___
*[ops/actions.go, line 36 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtZBUe9s-Xaogav7i1:-MGtZBUe9s-Xaogav7i2:b-4zanus) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L36)):*
> ```Go
> 			return true
> 		}
> 		ann := j
> ```

What does this do? How is `ann` used? This looks like an unused variable to me.
___
*[ops/actions.go, line 40 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtZGC75tIcjTC4ooat:-MGtZGC75tIcjTC4ooau:b6xm9mk) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L40)):*
> ```Go
> 		status, err := tk.GetStatus(j)
> 		if err != nil {
> 			return true // Hack
> ```

Please add a comment about how to unhack this.
___
*[ops/actions.go, line 150 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGt_Iip8FcvHlWf_xQH:-MGt_Iip8FcvHlWf_xQI:b-mvrsqc) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L150)):*
> ```Go
> 			details.TotalBytesProcessed/1000000, details.TotalBytesBilled/1000000)
> 		log.Println(msg)
> 		log.Printf("%s %s: %+v\n", op, j, details)
> ```

Multiple jobs could be processed simultaneously, right? Is there anything in these log lines to associate them if they're separated in the logs?  I'm thinking about using these logs for debugging. Is it possible to put them on the same line? Or to include some of the job info in the `msg` to track it back to a specific datatype/date?
___
*[ops/actions.go, line 363 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGta_Jm9_cHjWxcUtyk:-MGta_Jm9_cHjWxcUtyl:bd3smrm) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L363)):*
> ```Go
> 		return Success(j, "Annotation does not require join")
> 	}
> 	// TODO pass in the JobWithTarget, and get the base from the target.
> ```

what is "base" referring to?
___
*[ops/actions.go, line 384 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtamNHENUSDOjYsYis:-MGtamNHENUSDOjYsYit:bld19zp) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L384)):*
> ```Go
> 
> 	// Join job was successful.  Handle the statistics, metrics, tracker update.
> 	msg := interpretStatus("Join", j, status, delay)
> ```

can status be valid when `!outcome.IsDone()`? I'm wondering about monitoring BQ costs for failure conditions also.
___
*[ops/actions_test.go, line 51 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtbDsk-JkTAZ-tAojO:-MGtbDsk-JkTAZ-tAojP:bmc3jrd) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions_test.go#L51)):*
> ```Go
> 		nil,
> 		newStateFunc("-"),
> 		tracker.Copying)
> ```

Is it possible to add the "join" operation to this unit test?
___
*[ops/ops.go, line 128 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtb2tn0yR_zuD4wTZ2:-MGtb2tn0yR_zuD4wTZ3:bbhs3te) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/ops.go#L128)):*
> ```Go
> func (m *Monitor) AddAction(state tracker.State, cond ConditionFunc, op ActionFunc,
> 	successState tracker.State) {
> 	m.actions[state] = Action{
> ```

Yay for making things simpler!

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/314)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598 and @stephen-soltesz)

___
*[ops/actions.go, line 31 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGt_wPw9vQP5B54Zsfd:-MGtci4z6A9yURJqDZYv:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L31)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please choose a more descriptive function name. e.g. newAnnotationCondFunc?  `newCondFunc` is too generic to be clear about what's happening at call sites.
</blockquote></details>

Done.
___
*[ops/actions.go, line 33 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtZMaKCS3i4-6GudYs:-MGtciacEXlO6Czio8bK:b-896fix) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L33)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment -- I'm guessing this makes the annotation table always available to itself?
</blockquote></details>

Done.
___
*[ops/actions.go, line 36 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtZBUe9s-Xaogav7i1:-MGtc08J2j_L2bcApo0b:bzkph5) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L36)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What does this do? How is `ann` used? This looks like an unused variable to me.
</blockquote></details>

Thanks!  Also added comment
___
*[ops/actions.go, line 40 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtZGC75tIcjTC4ooat:-MGtcl9kBBsUNp-3D1al:b-upug7u) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment about how to unhack this.
</blockquote></details>

Better comment added.  It isn't really a hack after all.
___
*[ops/actions.go, line 150 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGt_Iip8FcvHlWf_xQH:-MGtcxfV0pBUiaADkSIQ:b-489uoi) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L150)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Multiple jobs could be processed simultaneously, right? Is there anything in these log lines to associate them if they're separated in the logs?  I'm thinking about using these logs for debugging. Is it possible to put them on the same line? Or to include some of the job info in the `msg` to track it back to a specific datatype/date?
</blockquote></details>

I will work on adding the job spec to each log.
___
*[ops/actions.go, line 363 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGta_Jm9_cHjWxcUtyk:-MGtd38_BdVT1UuXK2Hx:b-s578w3) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L363)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

what is "base" referring to?
</blockquote></details>

The base is tmp_ndt, which is currently hard coded.  However, the comment really belongs at NewTableOps call, and it is already there.  So I'll delete this one.
___
*[ops/actions.go, line 384 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtamNHENUSDOjYsYis:-MGtddUuDkfEwUNoc0he:b-f2hvdj) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions.go#L384)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

can status be valid when `!outcome.IsDone()`? I'm wondering about monitoring BQ costs for failure conditions also.
</blockquote></details>

Good point.  I'll add a TODO and an issue.

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/314)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[ops/actions_test.go, line 51 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtbDsk-JkTAZ-tAojO:-MGtfgJl7HUZwG85Q30B:b4w4v5z) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/actions_test.go#L51)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is it possible to add the "join" operation to this unit test?
</blockquote></details>

It already does.  Added better comments.
___
*[ops/ops.go, line 128 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/314#-MGtb2tn0yR_zuD4wTZ2:-MGtfn78DVZcn81-wLY5:bvr3fp0) ([raw file](https://github.com/m-lab/etl-gardener/blob/7bc68db432b9e688109bca0b9ef706a6ebf91d4f/ops/ops.go#L128)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Yay for making things simpler!
</blockquote></details>

You suggested it earlier, and I finally got around to it.  8-)

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/314#-:-MGu5vd_BMqV9oZDr3C7:bnfp4nl)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
