### PR TITLE
Fairly nasty ownership control code, through datastore.

### PR DESCRIPTION
**Pull request by gfr10598**
RETARGET and SUBMIT AFTER basic-2a
This is a bit of messy code for handling ownership reservations, yielding, taking over, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/7)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[.travis.yml, line 69 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5utAXACbTKxxmgvo6E:-L5utAXACbTKxxmgvo6F:bj1rdjy) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/.travis.yml#L69)):*
> ```YAML
>   for module in cloud/tq cloud/ds cmd/gardener ; do
>     go test -v -coverpkg=$COVER_PKGS -coverprofile=${module//\//_}.cov github.com/m-lab/etl-gardener/$module -tags=integration ;
>     EC=$[ $EC || $? ] ;
> ```

Does this work in travis if EC is not initialized?

```
A=$[ $A || $? ]

bash: || 0 : syntax error: operand expected (error token is "|| 0 ")
```

---

*[cloud/ds/ds.go, line 2 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uxe2aeDOykbo9DORA:-L5uxe2aeDOykbo9DORB:b-t18bpv) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L2)):*
> ```Go
> // Package ds defines utilities for working with datastore.
> package ds
> ```

`ds` is very short and ambiguous. Is there a more descriptive name?

This looks like a datastore "extention" package that makes common operations a little easier.

---

*[cloud/ds/ds.go, line 19 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uxJKFKkx_UfFWmljC:-L5uxJKFKkx_UfFWmljD:b-he3bhb) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L19)):*
> ```Go
> // ###############################################################################
> 
> // Saver is poorly named.  It is used for various DataStore load/save operations
> ```

`Env`?  Or, just `Client`, where the package name provides context. e.g. the package name could be "saver". `saver.Config` reads easily.

---

*[cloud/ds/ds.go, line 67 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uyqZ28d26kXSUFRiI:-L5uyqZ28d26kXSUFRiJ:bhqozlr) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L67)):*
> ```Go
> }
> 
> // OwnerLease is a DataStore record that controls ownership of the reprocessing task.
> ```

Expecting this to be a generic datastore package, I was surprised to see this in this file.

I can imagine that this logic will use the above datastore functions (so they could be private) or that these could be separate packages.

---

*[cloud/ds/ds.go, line 70 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uzQWOOPrWS9Q4be3T:-L5uzQWOOPrWS9Q4be3U:byqo8z3) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L70)):*
> ```Go
> // An instance must own this before doing any reprocessing / dedupping operations.
> // It should be periodically renewed to avoid another instance taking ownership.
> // TODO - should this have a mutex or other synchronization support?
> ```

It is the "mutex", right? Only one would exist per process, I'm imaging?

---

*[cloud/ds/ds_integration_test.go, line 17 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uzmVSleeGfHD43Hm0:-L5uzmVSleeGfHD43Hm1:bxdzgxk) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds_integration_test.go#L17)):*
> ```Go
> 	opts := []option.ClientOption{}
> 	if os.Getenv("TRAVIS") != "" {
> 		authOpt := option.WithCredentialsFile("../../travis-testing.key")
> ```

What do you think of using this PR to resolve https://github.com/m-lab/go/issues/11 rather than repeating a pattern we do not want to preserve?

Since we're placing raw SA keys in the travis environment now this actually should be simpler overall.

---

*[dispatch/dispatch.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v-u9zmP3qGh758Pjs:-L5v-u9zmP3qGh758Pjt:b-lzo7ww) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L50)):*
> ```Go
> // without a handshake.
> // TODO - should this have a mutex or other synchronization support?
> type OwnerLease struct {
> ```

OwnerLease is defined twice?

---

*[dispatch/dispatch.go, line 59 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v4mFS0lu7Z_sTQqNR:-L5v4mFS0lu7Z_sTQqNS:b-qb202b) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L59)):*
> ```Go
> // NewOwnerLease returns a properly initialized OwnerLease object.
> func NewOwnerLease() OwnerLease {
> 	hostname := os.Getenv("HOSTNAME")
> ```

Please describe what HOSTNAME provides beyond the GAE_INSTANCE value.

---

*[dispatch/dispatch.go, line 66 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v5ubIVMY5Rm1CJ7il:-L5v5ubIVMY5Rm1CJ7im:b-n9ae8c) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L66)):*
> ```Go
> 
> // Validate checks that fields have been initialized.
> func (ol *OwnerLease) Validate() error {
> ```

does this need to be public?

---

*[dispatch/dispatch.go, line 80 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v7AZniMrS8dD1UV9S:-L5v7AZniMrS8dD1UV9T:b-w2lcd2) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L80)):*
> ```Go
> // The receiver must have Hostname and InstanceID already set.
> // TODO - should this run on a timer, or in a go routine?
> func (ol *OwnerLease) Renew(saver *ds.Saver, interval time.Duration) error {
> ```

Does the public interface need to be larger than:

 * Lease()
 * Renew()

The lease may take as long as we want initially, and retry until we're sure we've failed.

The Renew would run continuously in the background, unless we know how to deliver shutdown signals?

How will we handle the case of partial deploys? e.g. AEFlex deploys a new version but the old instance is still running?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7)*

**Comment by stephen-soltesz** [comment]
If we want to guarantee that only a single instance ever runs, and control how the startup and shutdown process occurs, should we deploy etl-gardener to k8s instead of app-engine?

---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-:-L5vCOESFhfwmwH9-g8R:bm6vnuk)*

**Comment by stephen-soltesz** [comment]
App Engine is not designed to provide singletons, whereas k8s can.

---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-:-L5vCcMc6la-R0kHzKzS:b-b7qomz)*

**Comment by gfr10598** [comment]
This is a very good question.  I'd like to proceed with AppEngine, but discuss with you how much work/learning would be required to move it, possibly before deployment.

---

Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 69 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5utAXACbTKxxmgvo6E:-L5y7gio9n7WvYdemDQK:b75859) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/.travis.yml#L69)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does this work in travis if EC is not initialized?

```
A=$[ $A || $? ]

bash: || 0 : syntax error: operand expected (error token is "|| 0 ")
```
</blockquote></details>

It is initialized up above and still 0 if we reach this point.

---

*[cloud/ds/ds.go, line 2 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uxe2aeDOykbo9DORA:-L5yBUG4YHHFsj-EkGq0:b-l24evq) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`ds` is very short and ambiguous. Is there a more descriptive name?

This looks like a datastore "extention" package that makes common operations a little easier.
</blockquote></details>

Ok.  That is actually introduced in previous PR, so I will address it there.  I guess I used the wrong branch as base, and I'll fix that.

---

*[cloud/ds/ds.go, line 19 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uxJKFKkx_UfFWmljC:-L5y8c1o9mKCflzFoldF:b-bqkox) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L19)):*
> package name provides con
But the package name would then be misleading.  But I think Client might be good.

---

*[cloud/ds/ds.go, line 67 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uyqZ28d26kXSUFRiI:-L5y85Wp9I6QPMgXEhlP:buzm3ka) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L67)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Expecting this to be a generic datastore package, I was surprised to see this in this file.

I can imagine that this logic will use the above datastore functions (so they could be private) or that these could be separate packages.
</blockquote></details>

This slipped through.  Deleting it here.

---

*[cloud/ds/ds.go, line 70 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uzQWOOPrWS9Q4be3T:-L5y8C_0N4oHhi6rZPK0:btr5bz5) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds.go#L70)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It is the "mutex", right? Only one would exist per process, I'm imaging?
</blockquote></details>

Yes mutex is likely the right thing.  Not clear yet whether might need it for sync across go routines.

---

*[cloud/ds/ds_integration_test.go, line 17 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5uzmVSleeGfHD43Hm0:-L5yFFytzr_4YK6Znh3B:b-wfy8hk) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/cloud/ds/ds_integration_test.go#L17)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What do you think of using this PR to resolve https://github.com/m-lab/go/issues/11 rather than repeating a pattern we do not want to preserve?

Since we're placing raw SA keys in the travis environment now this actually should be simpler overall.
</blockquote></details>

Done, and much nicer.

---

*[dispatch/dispatch.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v-u9zmP3qGh758Pjs:-L5yA-4V8QbjZ1L413WG:b-r4dvd3) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

OwnerLease is defined twice?
</blockquote></details>

Deleted from ds

---

*[dispatch/dispatch.go, line 59 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v4mFS0lu7Z_sTQqNR:-L5yB-fZZussDCDaJnJ9:b-ja4b42) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L59)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please describe what HOSTNAME provides beyond the GAE_INSTANCE value.
</blockquote></details>

It was for debugging convenience, but it is a nonsense string, so removing it.

---

*[dispatch/dispatch.go, line 66 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v5ubIVMY5Rm1CJ7il:-L5yB4Nf2LQo1kXrGiFZ:bdehse1) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L66)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

does this need to be public?
</blockquote></details>

Nope.  Done.

---

*[dispatch/dispatch.go, line 80 at r2](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-L5v7AZniMrS8dD1UV9S:-L5yB6eh4SPtHoLViFdd:bmu7ybe) ([raw file](https://github.com/m-lab/etl-gardener/blob/2fd16719d36a83d244aeac5b2880cc2cada0d82e/dispatch/dispatch.go#L80)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Does the public interface need to be larger than:

 * Lease()
 * Renew()

The lease may take as long as we want initially, and retry until we're sure we've failed.

The Renew would run continuously in the background, unless we know how to deliver shutdown signals?

How will we handle the case of partial deploys? e.g. AEFlex deploys a new version but the old instance is still running?
</blockquote></details>

I've reduced it to these two plus Delete, for cleanup.  It could alternatively be implemented as part of Renew if you think that would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-:-L5yFe9N0DqpjZb7waQV:b-qzxl3w)*

**Comment by gfr10598** [comment]
I've split this into multiple PRs to decouple from older PRs, and simplify.
All changes to tq are deferred to next PR.
Datastore requirements are now embedded in OwnerLease instead of depending on ds package.

---

Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-:-L5zjvETsH3_VOCkKBVz:b-s4txab)*

**Comment by gfr10598** [comment]
PTAL

---

Review status: 0 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-:-L5zkiZd_69SYeZ0pRQV:bb71pro)*

**Comment by stephen-soltesz** [comment]
We discussed in person, and agreed to set this PR aside while we explore k8s as the singleton deployment strategy, where the datastore taskowner logic may not be necessary.

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/etl-gardener/7#-:-L5znjY2Su_U1lLOa9nR:b-gmimod)*

**Pull request closed without merging**
