### PR TITLE
Start plumbing Task state changes

### PR DESCRIPTION
**Pull request by gfr10598**
1. Fleshes out state.Saver implementation.
2. Adds Tasks state change actions in Dispatch, QueueHandler, DedupHandler, including tracking of most errors.

ALSO:
3. splits Dedup into two phases, one to launch the Dedup, and one to monitor whether it has finished successfully.  This allows tracking the JobID in the Task.
4. Improves queuehandler corner cases.
5. Improves unit tests.
6. Add git precommit for go files.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/47)

### CODE REVIEW

**Comment by gfr10598** [comment]
Part of Story #37

**Comment by pboothe** [comment]
Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cloud/tq/queuehandler.go, line 167 at r5](https://reviewable.io/reviews/m-lab/etl-gardener/47#-LDgTMi43f-BW2sHlurY:-LDgTMi43f-BW2sHlurZ:bfrd8iq) ([raw file](https://github.com/m-lab/etl-gardener/blob/0f877375a1c8e16114976c77c756799ec6061f23/cloud/tq/queuehandler.go#L167)):*
> ```Go
> 	for task := range qh.MsgChan {
> 		log.Println("Handling", task)
> 		task.Queue = qh.Queue
> ```

Can you just pass the task to the `qh.processOneRequest` function instead and have the queue handler write the queue name to the struct?

Also, is task.Queue ever read? I only see code that writes to that value.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/47)*

**Comment by gfr10598** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cloud/tq/queuehandler.go, line 167 at r5](https://reviewable.io/reviews/m-lab/etl-gardener/47#-LDgTMi43f-BW2sHlurY:-LDhSKif07tSw-NmCNqU:b-9nbk5k) ([raw file](https://github.com/m-lab/etl-gardener/blob/0f877375a1c8e16114976c77c756799ec6061f23/cloud/tq/queuehandler.go#L167)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Can you just pass the task to the `qh.processOneRequest` function instead and have the queue handler write the queue name to the struct?

Also, is task.Queue ever read? I only see code that writes to that value.
</blockquote></details>

The purpose of task is two-fold:
1.  Pass some state info to the "process" function.
2.  Maintain persistent state required for recovery on restart.

task.Queue will be read by the startup code, when a new instance starts up and reads the state from datastore.  That is a few PRs in the future though.  8-(

If you think this needs better comments, they should probably be added at where Task is defined in state.go.  Take a look there and see if you think more detail is needed, either there or maybe here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/47)*

**Comment by pboothe** [comment]
:lgtm:

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/47#-:-LDhUtmPBm351lilrgAy:bnfp4nl)*

**Pull request merged**
