### PR TITLE
Remove v1 logic from gardener

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change removes most v1 logic from the gardener system and associated packages.

Part of:
* https://github.com/m-lab/etl/issues/1084

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/382)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
First, I LOVE the coverage increase :heart_eyes_cat:.

I know a lot of this is just refactoring/deleting, but I'm finding it hard to understand everything that's happening given the size of the PR (see [guidelines](https://docs.google.com/document/d/10nepU9WO7580kO5kHDXWhnjZ9sty8KOZ7S7sVKlOrdg/edit?resourcekey=0-QJl_mpi1crS8NEZnYE680w#bookmark=id.s4n95i5irqut)). 

Is it possible to please break this down into smaller units with an appropriate description? (It's fine if not, but figured I'd ask).

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/382#-:-N4hSq6L7opbbvivRgiE:b-uquati)* status: 0 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
No problem, I'll split out the go 1.18 migration to begin.

**Review by stephen-soltesz — COMMENTED** [review]
I've added two reviewable comments to annotate significant changes. Nearly all other changes are removals or clarifying comments.

PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl-gardener/382#-:-N4hpaA1DdH2-Z_JLv-i:b-splbko)* status: 0 of 1 approvals obtained

___
*[`cloud/bq/dedup.go` line 16 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/382#-N4ho3O03-cx-ZSWk7bY:-N4ho3O03-cx-ZSWk7bZ:b-8zavfi) ([raw file](https://github.com/m-lab/etl-gardener/blob/4f9f9f19dfebfadc32eb581b3e35b9dd5656c9d0/cloud/bq/dedup.go#L16)):*
> ```Go
> // TODO(github.com/m-lab/etl/issues/1096)
> 
> // as mlab-oti:batch.ndt_20170601.
> ```

These variables are preserving dedup queries originally used for the unmigrated v1 datatypes, ndt.web100, sidestream, and paris traceroute. They are otherwise unused by the remaining gardener code.
___
*[`cloud/bq/ops.go` line 21 at r2](https://reviewable.io/reviews/m-lab/etl-gardener/382#-N4hoH3L6xgZjWggCuom:-N4hoH3L6xgZjWggCuon:bq0vp5j) ([raw file](https://github.com/m-lab/etl-gardener/blob/4f9f9f19dfebfadc32eb581b3e35b9dd5656c9d0/cloud/bq/ops.go#L21)):*
> ```Go
> var (
> 	// ErrTableNotFound is returned when trying to load to non-existent tmp tables.
> 	ErrTableNotFound = errors.New("table not found")
> ```

This error is used by this file, but was previously defined in dedup.go. This change simply puts the error in the file where it is referenced.

**Comment by stephen-soltesz** [comment]
Thank you!

**Pull request merged**
